#!/usr/bin/env python3
"""
Description
-----------
lnd_ocn_mesh_modifier is a tool that modifies lnd/ocn mesh files. It reads the
mesh files and outputs modified copies of the same files.

Current applications are limited to ones that use regular grid meshes, where
lnd and ocn share the same grid.

Files accessed
--------------
This wrapper script accesses
../../python/ctsm/lnd_ocn_mesh_modifier.py
../../python/ctsm/modify_lnd_ocn_meshes.py

Instructions
------------
To run on Cheyenne/Casper
1) Load the following to your local environment:
module load python
ncar_pylib
(Use "deactivate" to reverse the latter.)
2) Copy, then modify the configure file named modify_template.cfg, which
contains all the arguments needed by the script.
3) Run the script ./lnd_ocn_mesh_modifier pointing to the copied/modified
.cfg file, e.g. modify_users_copy.cfg

Example
-------
We specify one input grid because the tool can only modify regular grid meshes,
where lnd and ocn share the same grid.
>>> ./lnd_ocn_mesh_modifier modify_users_copy.cfg

Inputs
------
/glade/p/cesmdata/cseg/inputdata/share/meshes/fv0.9x1.25_141008_polemod_ESMFmesh.nc

Outputs
-------
./lnd_mesh_out.nc  # as named by user in the .cfg file
./ocn_mesh_out.nc  # as named by user in the .cfg file
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.modify_lnd_ocn_meshes.lnd_ocn_mesh_modifier import main

if __name__ == "__main__":
    main()
