#!/bin/bash
./xmlchange NEONSITE=TEAK
./xmlchange PTS_LON=240.99424199999999
./xmlchange PTS_LAT=37.006472
./xmlchange DATM_YR_ALIGN=2019
if [ $CLM_USRDAT_NAME=='NEON']
then
  ./xmlchange DATM_YR_START=2019
  # Different default start date and number of months to run for transient case
  #./xmlchange DATM_YR_START=2019
  if  [[ $compset =~ ^HIST ]]
  then
    ./xmlchange RUN_STARTDATE=2019-01-01
    ./xmlchange STOP_N=39
  fi
fi
