#!/bin/bash
#PBS -A P93300606
#PBS -N job_name
#PBS -j oe
#PBS -q premium
#PBS -l walltime=45:00
##PBS -l select=1:ncpus=36:mpiprocs=36
#PBS -l select=4:ncpus=36:mpiprocs=36
##PBS -l select=16:ncpus=36:mpiprocs=9
#PBS -o log.out

# note for -l input above
# -l select={num_nodes}:ncpus={max_tasks_per_node}:mpiprocs={tasks_per_node}

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

#module rm netcdf
#module load netcdf-mpi pnetcdf pio/2.5.5
#make

# -np {total_tasks}
cd /glade/u/home/mvertens/src/ctsm.toolchain/tools/mksurfdata_esmf/src/mksurfdata/run
mpiexec_mpt -np 144 /glade/u/home/mvertens/src/ctsm.toolchain/tools/mksurfdata_esmf/src/mksurfdata
