# -*- mode:Makefile -*-
#
# To generate all surface data sets, run:
# make -f Makefile.data all
#
# To generate a single dataset, run make with the name of the rule you
# want to build. For example, to generate the crop data set for 1x1_numaIA:
#
# make -f Makefile.data crop-numa
#
# NOTE: The default behavior is to parallelize data set creation using
# the batch system by submitting jobs to the interactive queue in the
# background. Standard out and standard error are redirected to a text
# file. To change this behavior, you can comment out the BATCHJOBS and
# BACKGROUND variables and replace them with empty variables.
#
# WARNING: Do not put more than one mksurfdata call per rule. output
# redirection is based on the rule name, and multiple rules will over
# write the previous output or incomprehensively merge output from
# simultaneously running jobs.
#
BATCHJOBS = execgy
BACKGROUND = &> $@.stdout.txt &

MKSURFDATA = $(BATCHJOBS) ./mksurfdata.pl

STANDARD_RES = 360x720cru,48x96,0.9x1.25,1.9x2.5,10x15,ne30np4

STANDARD = \
	global-present \
	global-present-45 \
	global-present-0.125 \
	global-present-ne16np4 \
	global-transient-rcp-2.6 \
	global-transient-rcp-4.5 \
	global-transient-rcp-6 \
	global-transient-rcp-8.5

TROPICS = \
	tropics-present \
	tropics-transient \
	tropics-atlantic-historical \
	tropics-atlantic-present \
	tropics-atlantic-transient

CROP = \
	crop-global-1.9 \
	crop-global-0.125 \
	crop-numa

all : standard tropics crop urban landuse-timeseries

#
# standard
#
standard : $(STANDARD)

global-present : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -res $(STANDARD_RES) $(BACKGROUND)

global-present-45 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -res 4x5 $(BACKGROUND)

global-present-0.125 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -res 0.125x0.125 $(BACKGROUND)

global-present-ne16np4 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -res ne16np4 $(BACKGROUND)

global-historical : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850 -res $(STANDARD_RES) $(BACKGROUND)

global-transient-rcp-2.6 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850-2100 -rcp 2.6 -res $(STANDARD_RES) $(BACKGROUND)

global-transient-rcp-4.5 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850-2100 -rcp 4.5 -res $(STANDARD_RES) $(BACKGROUND)

global-transient-rcp-6 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850-2100 -rcp 6   -res $(STANDARD_RES) $(BACKGROUND)

global-transient-rcp-8.5 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850-2100 -rcp 8.5 -res $(STANDARD_RES) $(BACKGROUND)

#
# tropics
#
tropics : $(TROPICS)

tropics-present : FORCE
	$(MKSURFDATA) -y 2000 -res 5x5_amazon,1x1_brazil -hirespft $(BACKGROUND)

tropics-transient : FORCE
	$(MKSURFDATA) -y 1850-2100 -rcp 8.5 -res 1x1_brazil $(BACKGROUND)

tropics-atlantic-historical : FORCE
	$(MKSURFDATA) -y 1850 -res 1x1_tropicAtl $(BACKGROUND)

tropics-atlantic-present : FORCE
	$(MKSURFDATA) -y 2000 -res 1x1_tropicAtl $(BACKGROUND)

tropics-atlantic-transient : FORCE
	$(MKSURFDATA) -y 1850-2005 -res 1x1_tropicAtl $(BACKGROUND)

#
# crop
#
crop : $(CROP)

crop-global-1.9 : FORCE
	$(MKSURFDATA) -crop -hirespft -glc_nec 10 -y 2000 -r 1.9x2.5 $(BACKGROUND)

# time series generates a surface data set with the same name, so we skip this one.
#crop-global-10 : FORCE
#	$(MKSURFDATA) -crop -hirespft -glc_nec 10 -y 2000 -r 10x15 $(BACKGROUND)

crop-global-0.125 : FORCE
	$(MKSURFDATA) -crop -hirespft -glc_nec 10 -y 2000 -r 0.125x0.125 $(BACKGROUND)

crop-numa : FORCE
	$(MKSURFDATA) -crop -hirespft -y 2000 -r 1x1_numaIA $(BACKGROUND)

# time series generates a surface data set with the same name, so we skip this one.
#crop-smallville : FORCE
#	$(MKSURFDATA) -crop -y 2000 -r 1x1_smallvilleIA \
#		-pft_idx 17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78 \
#		-pft_frc 6.5,1.5,1.6,1.7,1.8,1.9,1.5,1.6,1.7,1.8,1.9,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5 \
#		$(BACKGROUND)

#
# urban
#
urban : urban-present urban-alpha

urban-present : FORCE
	$(MKSURFDATA) -y 2000 -r 1x1_camdenNJ,1x1_vancouverCAN,1x1_mexicocityMEX $(BACKGROUND)

# NOTE(bja, 2015-01) skip abort on invalid data necessary as of 2015-01. See
# /glade/p/cesm/cseg/inputdata/lnd/clm2/surfdata_map/README_c141219
urban-alpha : FORCE
	$(MKSURFDATA) -y 2000 -r 1x1_urbanc_alpha -urban_skip_abort_on_invalid_data_check $(BACKGROUND)


#
# landuse timeseries
#
landuse-timeseries : landuse-timeseries-f10 landuse-timeseries-smallville

landuse-timeseries-f10 : FORCE
	$(MKSURFDATA) -crop -glc_nec 10 -y 1850-2005 -r 10x15 $(BACKGROUND)

landuse-timeseries-smallville : FORCE
	$(MKSURFDATA) -crop -y 1850-1855 -r 1x1_smallvilleIA \
		-pft_idx 17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78 \
		-pft_frc 6.5,1.5,1.6,1.7,1.8,1.9,1.5,1.6,1.7,1.8,1.9,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5 \
		-dynpft single_point_dynpft_files/landuse_timeseries_smallvilleIA_hist_simyr1850-1855.txt \
		$(BACKGROUND)

#
# clean up the working directory by removing generated files
#
clean : FORCE
	-rm *~

clobber : clean
	-rm surfdata_*.nc surfdata_*.log surfdata_*.namelist

#
# generic rule to force things to happen
#
FORCE :

