#!/bin/bash

./xmlchange NEONSITE=BARR
./xmlchange PTS_LON=203.349781
./xmlchange PTS_LAT=71.281711
./xmlchange DATM_YR_ALIGN=2019,DATM_YR_START=2019
# Different default start date and number of months to run for transient case
if  [[ $compset =~ ^HIST ]]; then
  ./xmlchange RUN_STARTDATE=2019-01-01
  if [[ $TEST != "TRUE" ]]; then
    ./xmlchange STOP_N=39
  fi
fi
