#!/usr/bin/env python3
"""
This is a just top-level skeleton script that calls
mesh_maker.py.
The original code (mesh_maker.py) is located under the
python/ctsm folder.

For full instructions on how to run the code and different options,
please check the python/ctsm/mesh_maker.py file.

----------------------------------------------------------------
Instructions for running using conda python environments:

../../py_env_create
conda activate ctsm_py
|------------------------------------------------------------------|
|---------------------  Instructions  -----------------------------|
|------------------------------------------------------------------|
This script creates ESMF unstructured GRID (mesh file) from a netcdf
file with valid lats and lons. Provided lats and lons can be 1D or 2D.

For example for running WRF-CTSM cases, the user can create a mesh
file for their domain :
    ./mesh_maker --input wrfinput_d01 --output my_region
        --lat XLAT --lon XLONG --verbose

"""
import os
import sys

# -- add python/ctsm  to path
_CTSM_PYTHON = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), os.pardir, os.pardir, "python"
)
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.mesh_maker import main

if __name__ == "__main__":
    main()
