#!/usr/bin/env python3
"""
This is a just top-level skeleton script that calls
modify_singlept_site_neon.py.
The original code (modify_singlept_site_neon.py) is located under
python/ctsm/site_and_regional folder.

For full instructions on how to run the code and different options,
please check python/ctsm/site_and_regional/modify_singlept_site_neon.py file.

This script is for modifying surface dataset at neon sites
using data available from the neon server.

After creating a single point surface data file from a global
surface data file using subset_data.py, use this script to
overwrite some fields with site-specific data for neon sites.

This script will do the following:
- Download neon data for the specified site if it does not exist
    in the specified directory : (i.e. ../../../neon_surf_files).
- Modify surface dataset with downloaded data.

----------------------------------------------------------------
To see all available options for modifying surface datasets at
tower sites:
    ./modify_singlept_site_neon --help
----------------------------------------------------------------
Instructions for running using conda python environments:
../../py_env_create
conda activate ctsm_pylib
"""

import os
import sys

# -- add python/ctsm  to path
_CTSM_PYTHON = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), os.pardir, os.pardir, "python"
)
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.site_and_regional.modify_singlept_site_neon import main

if __name__ == "__main__":
    main()
