#!/usr/bin/env python3
"""
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
#print (_CTSM_PYTHON)
sys.path.insert(1, _CTSM_PYTHON)


from ctsm.subset_data import main

if __name__ == "__main__":
    main()
