# https://pre-commit.com

exclude: tools/contrib/.*|.*\.svg|.*\.png|.*\.jpg|.*\.jpeg|.lib
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        files: python/ cime_config/SystemTests/ cime_config/buildlib cime_config/buildnml
      - id: trailing-whitespace
        files: python/ cime_config/SystemTests/ cime_config/buildlib cime_config/buildnml
      - id: check-yaml
        files: / python/ lilac/ .github/
      - id: check-xml
        exclude: src/fates/.*|components/.*|env_mach_specific.xml|cime/.*|ccs_config/.*|libraries/.*
      - id: debug-statements
        files: python/ cime_config/SystemTests/ cime_config/buildlib cime_config/buildnml
      - id: mixed-line-ending
        files: python/ cime_config/SystemTests/ cime_config/buildlib cime_config/buildnml
      - id: check-added-large-files
      # These two showed lot's of issues so should be worked on before turning on
      #- id: check-executables-have-shebangs
      #  exclude: shell_commands
      #- id: check-shebang-scripts-are-executable
      #  exclude: shell_commands
      - id: check-merge-conflict
      - id: check-docstring-first
        files: python/ cime_config/SystemTests/ cime_config/buildlib cime_config/buildnml
# black as python formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: python/ cime_config/SystemTests/ cime_config/buildlib cime_config/buildnml
        args: [--config python/pyproject.toml]
