#!/usr/bin/env python3
"""
For description and instructions, please see the CTSM User's Guide.
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.modify_input_files.mesh_mask_modifier import main

if __name__ == "__main__":
    main()
