#!/usr/bin/env perl
#-----------------------------------------------------------------------------------------------
#
# build-namelist
#
# This script builds the namelists for CLM
#
# The simplest use of build-namelist is to execute it from the build directory where configure
# was run.  By default it will use the config_cache.xml file that was written by configure to
# determine the build time properties of the executable, and will write the files that contain 
# the output namelists in that same directory.  But if multiple runs are to made using the
# same executable, successive invocations of build-namelist will overwrite previously generated
# namelist files.  So generally the best strategy is to invoke build-namelist from the run
# directory and use the -config option to provide the filepath of the config_cache.xml file.
#
#
# Date        Contributor      Modification
# -------------------------------------------------------------------------------------------
# 2009-01-20  Vertenstein      Original version
#--------------------------------------------------------------------------------------------

use strict;
#use warnings;
#use diagnostics;

use Cwd;
use English;
use Getopt::Long;
use IO::File;
#-----------------------------------------------------------------------------------------------

sub usage {
    die <<EOF;
SYNOPSIS
     build-namelist [options]
OPTIONS
     -clm_demand "list"       List of variables to require on clm namelist besides the usuals.
                              "-clm_demand list" to list valid options.
                              (can include a list member "null" which does nothing)
     -clm_usr_name     "name" Dataset resolution/descriptor for personal datasets. Default: not used
                              Example: 1x1pt_boulderCO_c090722 to describe location,
                                       number of pts, and date files created
     -config "filepath"       Read the given CICE configuration cache file. Default: "config_cache_cice.xml".
     -csmdata "dir"           Root directory of CCSM input data.
                              Can also be set by using the CSMDATA environment variable.
     -d "directory"           Directory where output namelist file will be written
                              Default: current working directory.
     -help [or -h]            Print usage to STDOUT.
     -ignore_ic_date          Ignore the date on the initial condition files (ic_ymd and ic_tod) 
                              when determining what input initial condition file to use.
     -ignore_ic_year          Ignore just the year part of the date on the initial condition files (ic_ymd and ic_tod) 
                              when determining what input initial condition file to use.
     -infile "filepath"       Specify a file containing namelists to read values from.
     -inputdata "filepath"    Writes out a list containing pathnames for required input datasets in
                              file specified.
     -lnd_res "resolution"    Horizontal resolution of fine mesh for land 
                              (if different than resolution coupling to atmosphere)
                              Use nlatxnlon for spectral grids;  dlatxdlon for fv grids 
			      (dlat and dlon are the grid cell size in degrees for latitude and longitude).
     -mask "landmask"         Type of land-mask (default, navy, gx3v5, gx1v5 etc.)
                              "-mask list" to list valid land masks.
     -namelist "namelist"     Specify namelist settings directly on the commandline by supplying 
                              a string containing FORTRAN namelist syntax, e.g.,
                                 -namelist "&clm_inparm dt=1800 /"
     -rcp "value"             Representative concentration pathway (rcp) to use for future scenarios.
     -res "resolution"        Specify horizontal grid.  Use nlatxnlon for spectral grids;
                              dlatxdlon for fv grids (dlat and dlon are the grid cell size
    			      in degrees for latitude and longitude respectively)
                              "-res list" to list valid resolutions.
     -s                       Turns on silent mode - only fatal messages issued.
     -sim_year "year"         Year to simulate for input datasets (i.e. 1850, 2000, 1850-2000, 1850-2100)
                              "-sim_year list" to list valid simulation years
     -start_type "type"       Type of simulation (cold, arb_ic, startup, continue, or branch)
                              (cold=always start with arbitrary initial conditions)
                              (arb_ic=start with arbitrary initial conditions if initial conditions don't exist)
                              (startup=ensure that initial conditions are being used)
     -test                    Enable checking that input datasets exist on local filesystem.
     -verbose [or -v]         Turn on verbose echoing of informational messages.
     -use_case "case"         Specify a use case which will provide default values.
                              "-use_case list" to list valid use-cases.
     -version                 Echo the SVN tag name used to check out this CLM distribution.

OPTIONS used ONLY for clm standalone testing: (i.e. ONLY used when mode=ccsm_seq)

     -drv_case "name"         Case identifier up to 32 characters
     -datm_cycle_beg_year  "year"  The begining year to cycle input datasets over.
     -datm_cycle_end_year  "year"  The ending year to cycle input datasets over.
     -datm_cycle_init_year "year"  The simulation year that will correspond to the data for cycle_beg_year.
     -datm_data_dir "path"    Directory path to the datm data
     -datm_domain "file"      File name of domain file for datm data matching 
                              resolution data resolution.
     -datm_dom_dir "path"     Directory path to the datm_domain file.
     -datm_source "source"    Source data to use for datm (for ccsm_seq mode)
                              "-datm_source list" to list valid datm_source types.
     -drv_runlength "length"  Length of simulation (e.g. default, 10d, 5s, 2y)
                              (Corresponding to: default, 10 days, 5 steps, or 2 years)
                              classifiers (d=days, s=steps, y=years)


Note: The precedence for setting the values of namelist variables is (highest to lowest):
      0. namelist values set by specific command-line options, i.e., -d, -sim_year
      1. values set from a use-case scenario, e.g., -use_case
      2. values set on the command-line using the -namelist option,
      3. values read from the file specified by -infile,
      4. values from the namelist defaults file.
EOF
}

#-----------------------------------------------------------------------------------------------
# Set the directory that contains the CLM configuration scripts.  If the command was
# issued using a relative or absolute path, that path is in $ProgDir.  Otherwise assume the
# command was issued from the current working directory.

(my $ProgName = $0) =~ s!(.*)/!!;      # name of this script
my $ProgDir = $1;                      # name of directory containing this script -- may be a
                                       # relative or absolute path, or null if the script is in
                                       # the user's PATH
my $cmdline = "@ARGV";                 # Command line arguments to script
my $cwd = getcwd();                    # current working directory
my $cfgdir;                            # absolute pathname of directory that contains this script
my $nm = "ProgName::";                 # name to use if script dies
if ($ProgDir) { 
    $cfgdir = absolute_path($ProgDir);
} else {
    $cfgdir = $cwd;
}

my $cfg_cache = "config_cache.xml";       # Default name of configuration cache file
my $outdirname = "$cwd";                  # Default name of output directory name

#-----------------------------------------------------------------------------------------------

# Process command-line options.

my %opts = ( config                => $cfg_cache,
	     csmdata               => undef,
	     clm_usr_name          => undef,
             datm_cycle_beg_year   => "default",
             datm_cycle_end_year   => "default",
             datm_cycle_init_year  => "default",
             clm_demand            => "null",
	     help                  => 0,
	     dir                   => $outdirname,
	     rcp                   => "default",
             sim_year              => "default",
	     res                   => "default",
	     lnd_res               => "default",
	     silent                => 0,
             datm_source           => "default",
             mask                  => "default",
	     test                  => 0,
	    );

GetOptions(
    "drv_case=s"                => \$opts{'drv_case'},
    "clm_demand=s"              => \$opts{'clm_demand'},
    "config=s"                  => \$opts{'config'},
    "csmdata=s"                 => \$opts{'csmdata'},
    "clm_usr_name=s"            => \$opts{'clm_usr_name'},
    "datm_cycle_beg_year=s"     => \$opts{'datm_cycle_beg_year'},
    "datm_cycle_end_year=s"     => \$opts{'datm_cycle_end_year'},
    "datm_cycle_init_year=s"    => \$opts{'datm_cycle_init_year'},
    "datm_data_dir=s"           => \$opts{'datm_data_dir'},
    "datm_domain=s"             => \$opts{'datm_domain'},
    "datm_dom_dir=s"            => \$opts{'datm_dom_dir'},
    "d|d=s"                     => \$opts{'dir'},
    "h|help"                    => \$opts{'help'},
    "lnd_res=s"                 => \$opts{'lnd_res'},
    "ignore_ic_date"            => \$opts{'ignore_ic_date'},
    "ignore_ic_year"            => \$opts{'ignore_ic_year'},
    "infile=s"                  => \$opts{'infile'},
    "inputdata=s"               => \$opts{'inputdata'},
    "mask=s"                    => \$opts{'mask'},
    "namelist=s"                => \$opts{'namelist'},
    "res=s"                     => \$opts{'res'},
    "rcp=s"                     => \$opts{'rcp'},
    "drv_runlength=s"           => \$opts{'drv_runlength'},
    "s|silent"                  => \$opts{'silent'},
    "sim_year=s"                => \$opts{'sim_year'},
    "start_type=s"              => \$opts{'start_type'},
    "datm_source=s"             => \$opts{'datm_source'},
    "test"                      => \$opts{'test'},
    "use_case=s"                => \$opts{'use_case'},
    "v|verbose"                 => \$opts{'verbose'},
    "version"                   => \$opts{'version'},
)  or usage();

# Give usage message.
usage() if $opts{'help'};

# Echo version info.
version($cfgdir) if $opts{'version'};    

# Check for unparsed arguments
if (@ARGV) {
    print "ERROR: unrecognized arguments: @ARGV\n";
    usage();
}

# Define print levels:
# 0 - only issue fatal error messages
# 1 - only informs what files are created (default)
# 2 - verbose
my $print = 1;
if ($opts{'silent'})  { $print = 0; }
if ($opts{'verbose'}) { $print = 2; }
my $eol = "\n";

if ($print>=2) { print "Setting CLM configuration script directory to $cfgdir$eol"; }

# Check that configuration cache file exists.
(-f $opts{'config'})  or  die <<"EOF";
** $ProgName - Cannot find configuration cache file: \"$opts{'config'}\" **
EOF

if ($print>=2) { print "Using CLM configuration cache file $opts{'config'}$eol"; }


# Add the location of the use case defaults files to the options hash
$opts{'use_case_dir'} = "$cfgdir/namelist_files/use_cases";

#-----------------------------------------------------------------------------------------------
# Make sure we can find required perl modules, definition, and defaults files.
# Look for them under the directory that contains the configure script.

# The root directory for the input data files must be specified.

#The root directory to ccsm utils Tools
my $ccsm_tools = &absolute_path( "$cfgdir/../../../../scripts/ccsm_utils/Tools" );

# The XML::Lite module is required to parse the XML files.
(-f "$ccsm_tools/perl5lib/XML/Lite.pm")  or  die <<"EOF";
** $ProgName - Cannot find perl module \"XML/Lite.pm\" in directory 
    \"$ccsm_tools/perl5lib\" **
EOF

# The Build::Config module provides utilities to access the configuration information
# in the config_cache.xml file
(-f "$ccsm_tools/perl5lib/Build/Config.pm")  or  die <<"EOF";
** $ProgName - Cannot find perl module \"Build/Config.pm\" in directory 
    \"$ccsm_tools/perl5lib\" **
EOF

# The namelist definition file contains entries for all namelist variables that
# can be output by build-namelist.
my $nl_definition_file = "$cfgdir/namelist_files/namelist_definition.xml";
(-f "$nl_definition_file")  or  die <<"EOF";
** $ProgName - Cannot find namelist definition file \"$nl_definition_file\" **
EOF
if ($print>=2) { print "Using namelist definition file $nl_definition_file$eol"; }

# The Build::NamelistDefinition module provides utilities to validate that the output
# namelists are consistent with the namelist definition file
(-f "$ccsm_tools/perl5lib/Build/NamelistDefinition.pm")  or  die <<"EOF";
** $ProgName - Cannot find perl module \"Build/NamelistDefinition.pm\" in directory 
    \"$ccsm_tools/perl5lib\" **
EOF

# The namelist defaults file contains default values for all required namelist variables.
my @nl_defaults_files = ( "$cfgdir/namelist_files/namelist_defaults_overall.xml", 
                          "$cfgdir/namelist_files/namelist_defaults_clm.xml", 
                          "$cfgdir/namelist_files/namelist_defaults_drv.xml",
                          "$cfgdir/namelist_files/namelist_defaults_datm.xml" );

if (defined $opts{'use_case'}) {
   if ( $opts{'use_case'} ne "list" ) {
      unshift( @nl_defaults_files, "$opts{'use_case_dir'}/$opts{'use_case'}.xml" );
   }
}

foreach my $nl_defaults_file ( @nl_defaults_files ) {
  (-f "$nl_defaults_file")  or  die <<"EOF";
** $ProgName - Cannot find namelist defaults file \"$nl_defaults_file\" **
EOF
  if ($print>=2) { print "Using namelist defaults file $nl_defaults_file$eol"; }
}

# The Build::NamelistDefaults module provides a utility to obtain default values of namelist
# variables based on finding a best fit with the attributes specified in the defaults file.
(-f "$ccsm_tools/perl5lib/Build/NamelistDefaults.pm")  or  die <<"EOF";
** $ProgName - Cannot find perl module \"Build/NamelistDefaults.pm\" in directory 
    \"$ccsm_tools//perl5lib\" **
EOF

# The Build::Namelist module provides utilities to parse input namelists, to query and modify
# namelists, and to write output namelists.
(-f "$ccsm_tools/perl5lib/Build/Namelist.pm")  or  die <<"EOF";
** $ProgName - Cannot find perl module \"Build/Namelist.pm\" in directory 
    \"$ccsm_tools/perl5lib\" **
EOF

#-----------------------------------------------------------------------------------------------
# Add $cfgdir/perl5lib to the list of paths that Perl searches for modules
my @dirs = ( $cfgdir, "$ccsm_tools/perl5lib");
unshift @INC, @dirs;
require XML::Lite;
require Build::Config;
require Build::NamelistDefinition;
require Build::NamelistDefaults;
require Build::Namelist;
require Streams::Template;
#-----------------------------------------------------------------------------------------------
# Create a configuration object from the CLM config_cache.xml file. 
my $cfg = Build::Config->new($opts{'config'});

# Validate some of the commandline option values.
validate_options("commandline", $cfg, \%opts);

# Create a namelist definition object.  This object provides a method for verifying that the
# output namelist variables are in the definition file, and are output in the correct
# namelist groups.
my $definition = Build::NamelistDefinition->new($nl_definition_file);

# Create a namelist defaults object.  This object provides default values for variables
# contained in the input defaults file.  The configuration object provides attribute
# values that are relevent for the CLM executable for which the namelist is being produced.
my $defaults = Build::NamelistDefaults->new( shift( @nl_defaults_files ), $cfg);
foreach my $nl_defaults_file ( @nl_defaults_files ) {
   $defaults->add( "$nl_defaults_file" );
}

#
# List valid values if asked for
#
list_options( $cfg, \%opts );

# Create an empty namelist object.  Add values to it in order of precedence.
my $nl = Build::Namelist->new();

# Check that the CCSM inputdata root directory has been specified.  This must be
# a local or nfs mounted directory.
my $inputdata_rootdir = undef;
if (defined($opts{'csmdata'})) {
    $inputdata_rootdir = $opts{'csmdata'};
}
elsif (defined $ENV{'CSMDATA'}) {
    $inputdata_rootdir = $ENV{'CSMDATA'};
}
else {
    die "$ProgName - ERROR: CCSM inputdata root directory must be specified by either -csmdata argument\n" .
	" or by the CSMDATA environment variable. :";
}
if ( $ENV{'DIN_LOC_ROOT'} eq "" ) {
   $ENV{'DIN_LOC_ROOT'} = $inputdata_rootdir;
}

if ($opts{'test'}) {
    (-d $inputdata_rootdir)  or  die <<"EOF";
** $ProgName - CCSM inputdata root is not a directory: \"$inputdata_rootdir\" **
EOF
}
my $test_files = $opts{'test'};

if ($print>=2) { print "CCSM inputdata root directory: $inputdata_rootdir$eol"; }
#-----------------------------------------------------------------------------------------------

# Some regular expressions...
###my $TRUE  = qr/\.true\./i;
###my $FALSE = qr/\.false\./i;
# **N.B.** the use of qr// for precompiling regexps isn't supported until perl 5.005.
my $TRUE  = '\.true\.';
my $FALSE = '\.false\.';

#-----------------------------------------------------------------------------------------------

# Process the user input in order of precedence.  At each point we'll only add new
# values to the namelist and not overwrite previously specified specified values which
# have higher precedence.

# Process the -use_case arg.

if (defined $opts{'use_case'}) {

    # The use case definition is contained in an xml file with the same format as the defaults file.
    # Create a new NamelistDefaults object.
    my $uc_defaults = Build::NamelistDefaults->new("$opts{'use_case_dir'}/$opts{'use_case'}.xml", $cfg);

    # Loop over the variables specified in the use case.
    # Add each one to the namelist.
    my @vars = $uc_defaults->get_variable_names();
    foreach my $var (@vars) {
	my $val = $uc_defaults->get_value($var);

        print "adding use_case $opts{'use_case'} defaults for var $var with val $val \n";

	if ($val) {
	    add_default($nl, $var, 'val'=>$val);
	} else {
	    die "$ProgName - ERROR: No default value found for variable $var in '-use_case' $opts{'use_case'}.\n $@";
	}
    }
}

# Process the commandline args that provide specific namelist values.

# Process the -namelist arg.

if (defined $opts{'namelist'}) {
    # Parse commandline namelist
    my $nl_arg = Build::Namelist->new($opts{'namelist'});

    # Validate input namelist -- trap exceptions
    my $nl_arg_valid;
    eval { $nl_arg_valid = $definition->validate($nl_arg); };
    if ($@) {
	die "$ProgName - ERROR: Invalid namelist variable in commandline arg '-namelist'.\n $@";
    }

    # Merge input values into namelist.  Previously specified values have higher precedence
    # and are not overwritten.
    $nl->merge_nl($nl_arg_valid);
}

# Process the -infile arg.

if (defined $opts{'infile'}) {
    # Parse namelist input from a file
    my $nl_infile = Build::Namelist->new($opts{'infile'});

    # Validate input namelist -- trap exceptions
    my $nl_infile_valid;
    eval { $nl_infile_valid = $definition->validate($nl_infile); };
    if ($@) {
	die "$ProgName - ERROR: Invalid namelist variable in '-infile' $opts{'infile'}.\n $@";
    }

    # Merge input values into namelist.  Previously specified values have higher precedence
    # and are not overwritten.
    $nl->merge_nl($nl_infile_valid);
}


#-----------------------------------------------------------------------------------------------

my $val;

# Determine mode from config file

my $mode = $cfg->get('mode');
if ($print>=2) { print "CLM mode is $mode $eol"; }

# Get PIO mode
my $pio = $cfg->get('pio');

# Get BGC mode

my $bgc = $cfg->get('bgc');

# Get max number of Plant function types
my $maxpft = $cfg->get('maxpft');

# Obtain default values for the following build-namelist input arguments

my $val;
my $res;
my $group;
my $var;

$var = "res";
if ( $opts{$var} ne "default" ) {
    $val = $opts{$var};
} else {
    $val= $defaults->get_value($var);
}
$res = $val;
if ($print>=2) { print "CLM atm resolution is $res $eol"; }
$opts{$var} = $val;
$val = &quote_string( $res );
$group = $definition->get_group_name($var);
#$nl->set_variable_value($group, $var, $val);
if (  ! $definition->is_valid_value( $var, $val ) ) {
   my @valid_values   = $definition->get_valid_values( $var );
   if ( ! defined($opts{'clm_usr_name'}) || $res ne $opts{'clm_usr_name'} ) {
      die "$nm $var has a value ($val) that is NOT valid. Valid values are: @valid_values\n";
   }
}

$var = "mask";
if ( $opts{$var} ne "default" ) {
    $val = $opts{$var};
} else {
    my %opts = ( 'hgrid'=>$res );
    $val = $defaults->get_value($var, \%opts );
}
my $mask = $val;
$opts{'mask'} = $mask;
$val = &quote_string( $val );
$group = $definition->get_group_name($var);
$nl->set_variable_value($group, $var, $val);
if (  ! $definition->is_valid_value( $var, $val ) ) {
   my @valid_values   = $definition->get_valid_values( $var );
   die "$nm $var has a value ($val) that is NOT valid. Valid values are: @valid_values\n";
}
if ($print>=2) { print "CLM land mask is $mask $eol"; }

$var = "rcp";
if ( $opts{$var} ne "default" ) {
    $val = $opts{$var};
} else {
    $val = $defaults->get_value($var);
}
my $rcp = $val;
$opts{'rcp'} = $rcp;
$group = $definition->get_group_name($var);
$nl->set_variable_value($group, $var, $val);
if (  ! $definition->is_valid_value( $var, $val ) ) {
   my @valid_values   = $definition->get_valid_values( $var );
   die "$nm $var has a value ($val) that is NOT valid. Valid values are: @valid_values\n";
}
if ($print>=2) { print "CLM future scenario representative concentration is $rcp $eol"; }

my $var = "sim_year";
if ( $opts{$var} ne "default" ) {
    $val = $opts{$var};
} else {
    $val = $defaults->get_value($var);
} 
my $sim_year_range = $defaults->get_value("sim_year_range");
my $sim_year       = $val;
if ( $val =~ /([0-9]+)-([0-9]+)/ ) { 
   $sim_year       = $1; 
   $sim_year_range = $val;
}
$val = $sim_year;
$group = $definition->get_group_name($var);
$nl->set_variable_value($group, $var, $val );
if (  ! $definition->is_valid_value( $var, $val, 'noquotes'=>1 ) ) {
   my @valid_values   = $definition->get_valid_values( $var );
   die "$nm $var of $val is NOT valid. Valid values are: @valid_values\n";
}
$nl->set_variable_value($group, $var, $val );
if ($print>=2) { print "CLM sim_year is $sim_year $eol"; }

my $var = "sim_year_range";
$val = $sim_year_range;
if ( $val ne "constant" ) {
   $opts{$var}   = $val;
   $group = $definition->get_group_name($var);
   $nl->set_variable_value($group, $var, $val );
   if (  ! $definition->is_valid_value( $var, $val, 'noquotes'=>1 ) ) {
      my @valid_values   = $definition->get_valid_values( $var );
      die "$nm $var of $val is NOT valid. Valid values are: @valid_values\n";
   }
   $val = "'".$defaults->get_value($var)."'";
   $nl->set_variable_value($group, $var, $val );
   if ($print>=2) { print "CLM sim_year_range is $sim_year_range $eol"; }
}

my $lnd_res;
if ($opts{'lnd_res'} eq "default") { 
    $lnd_res = $res;
} else {
    $lnd_res = $opts{'lnd_res'};
}
if ($print>=2) { print "CLM land resolution is $lnd_res $eol"; }
$opts{'lnd_res'} = $lnd_res;
my $var = "res";
my $val = &quote_string( $res );
my $group = $definition->get_group_name($var);
#$nl->set_variable_value($group, $var, $val);
if (  ! $definition->is_valid_value( $var, $val ) ) {
   my @valid_values   = $definition->get_valid_values( $var );
   if ( ! defined($opts{'clm_usr_name'}) || $res ne $opts{'clm_usr_name'} ) {
      die "$nm lnd_res has a value ($val) that is NOT valid. Valid values are: @valid_values\n";
   }
}

# Process the -clm_usr_name argument
if (defined $opts{'clm_usr_name'}) {
    # The user files definition is contained in an xml file with the same format as the defaults file.
    
    # The one difference is that variables are expanded.
    # Create a new NamelistDefaults object.
    my $nl_defaults_file = "$cfgdir/namelist_files/namelist_defaults_usr_files.xml";
    my $uf_defaults = Build::NamelistDefaults->new("$nl_defaults_file", $cfg );
    # Loop over the variables specified in the user files
    # Add each one to the namelist.
    my @vars = $uf_defaults->get_variable_names();
    my %settings;
    $settings{'mask'}           = $mask;
    $settings{'sim_year'}       = $sim_year;
    $settings{'sim_year_range'} = $sim_year_range;
    $settings{'clm_usr_name'}   = $opts{'clm_usr_name'};
    if ( $inputdata_rootdir eq "\$DIN_LOC_ROOT" ) {
       $settings{'csmdata'}     = $ENV{'DIN_LOC_ROOT'};
    } else {
       $settings{'csmdata'}     = $inputdata_rootdir;
    }

    my $nvars = 0;
    foreach my $var (@vars) {
	my $val = $uf_defaults->get_usr_file($var, $definition, \%settings);

	if ($val) {
            print "adding clm user file defaults for var $var with val $val \n";
	    add_default($nl, $var, 'val'=>$val);
            $nvars++;
	}
    }
    if ( $nvars == 0 ) {
         die "$nm setting clm_usr_name -- but did NOT find any user datasets: $opts{'clm_usr_name'}\n";
    }
}

# Add default values for required namelist variables that have not been previously set.
# This is done either by using the namelist default object, or directly with inline logic.


#######################################
# namelist group: seq_infodata_inparm #
#######################################

# Run type for driver namelist - note that arb_ic implies that the run is startup
my $var = "start_type";
my $start_type = $nl->get_value($var);
if (defined $opts{$var}) { 
    $start_type = $opts{$var};
    if ($opts{$var} eq "cold" || $opts{$var} eq "arb_ic") {
       add_default($nl, $var, 'val'=>'startup'); 
    } else {
       add_default($nl, $var, 'val'=>$opts{$var}); 
    }
} else {
    add_default($nl, $var );
    $start_type = $nl->get_value($var);
}

if ($mode eq "ccsm_seq") {

   # Case name
   if (defined $opts{'drv_case'}) {
       add_default($nl, 'case_name', 'val'=>$opts{'drv_case'});
   } else {
       add_default($nl, 'case_name');
   }
   # Case description
   my $case_desc  = $nl->get_value('case_desc');
   if ( $case_desc eq "" ) {
      if (defined $opts{'use_case'}) {
         add_default($nl, 'case_desc', 'val'=>$nl->get_value("use_case_desc") );
      } else {
         add_default($nl, 'case_desc', 'nofail'=>1 );
      }
   }

   # Output path root directory
   add_default($nl, 'outpathroot', 'val'=>$opts{'dir'}."/"); 
   
   # Orbit
   # If orbital parameters have not been specified then set default orbital year.
   # If NOT all of obliq, eccen and mvelp are specified -- return an error.
   
   if (not defined $nl->get_value('orb_obliq') and
       not defined $nl->get_value('orb_eccen') and
       not defined $nl->get_value('orb_mvelp')     ) {
         add_default($nl, 'orb_iyear_ad');
   } else {
      if (not defined $nl->get_value('orb_obliq') or
          not defined $nl->get_value('orb_eccen') or
          not defined $nl->get_value('orb_mvelp')     ) {
         die "$nm when setting orbit, ALL of orb_obliq, orb_eccen, AND orb_mvelp MUST be set\n";
      }
   }

   add_default($nl, 'model_version' );
   add_default($nl, 'hostname', 'val'=>`hostname` );
   add_default($nl, 'username', 'val'=>$ENV{'LOGNAME'} );
   add_default($nl, 'timing_dir' );
   add_default($nl, 'tchkpt_dir' );
   add_default($nl, 'eps_frac'   );
   add_default($nl, 'eps_amask'  );
   add_default($nl, 'eps_aarea'  );
   
   if ( $start_type =~ /branch/ ) {
      if ( not defined $nl->get_value('restart_file') ) {
         die "$nm restart_file MUST be set when start_type equals branch\n";
      }
   }

   # Only one of these can be set to .true.
   if (defined $nl->get_value('atm_adiabatic')     or
       defined $nl->get_value('aqua_planet')       or
       defined $nl->get_value('atm_ideal_physics') ) {
          my $atm_adiabatic     = $nl->get_value('atm_adiabatic');
          my $atm_ideal_physics = $nl->get_value('atm_ideal_physics');
          my $aqua_planet       = $nl->get_value('aqua_planet');
          my $t = 0;
          if ( defined( $atm_adiabatic ) ) { 
              if ( $atm_adiabatic     =~ /$TRUE/i ) { $t++; }
          }
          if ( defined( $aqua_planet) ) { 
              if ( $aqua_planet       =~ /$TRUE/i ) { $t++; }
          }
          if ( defined( $atm_ideal_physics) ) { 
              if ( $atm_ideal_physics =~ /$TRUE/i ) { $t++; }
          }
          if ( $t > 1 ) {
             die "$nm only one of atm_adiabatic, atm_ideal_phys and aqua_planet" . 
                 " can be set to true.\n";
          }
   }
}

############################
# namelist group: ccsm_pes #
############################
if ($mode eq "ccsm_seq") {

   # By default the driver sets all components to use all tasks.  This is the
   # appropriate default for the standalone CLM configuration.

   # By default the driver sets all components to use 1 thread.  This should be
   # reset either to user specified values, or by default use the OMP_NUM_THREADS
   # environment variable to set the thread count for each component.

   # Is this an smp build?
   my $smp = $cfg->get('smp');
   if ($smp) {

       # If user has set the specific variables for component threads on the commandline
       # those values will be used.  If not, the value of the environment variable 
       # OMP_NUM_THREADS will be used.
   
       # Check for OMP_NUM_THREADS
       my $nthreads;
       if (defined $ENV{'OMP_NUM_THREADS'}) {
	   $nthreads = $ENV{'OMP_NUM_THREADS'};
       }

       if ($nthreads) {
	   add_default($nl, 'atm_nthreads', 'val'=>$nthreads);
	   add_default($nl, 'cpl_nthreads', 'val'=>$nthreads);
	   add_default($nl, 'lnd_nthreads', 'val'=>$nthreads);
	   add_default($nl, 'ice_nthreads', 'val'=>1        );
	   add_default($nl, 'ocn_nthreads', 'val'=>1        );
       }
   }
}

######################################
# namelist group: seq_timemgr_inparm #
######################################

if ($mode eq "ccsm_seq") {
   # Length of simulation
   if ( defined $opts{'drv_runlength'} ) {
       if ( $opts{'drv_runlength'} =~ /^([1-9][0-9]*)([sdy])$/ ) {
	   my %options = ( s=>"nsteps", d=>"ndays", y=>"nyears" );
	   add_default($nl, "stop_n"     , 'val'=>$1 );
	   add_default($nl, "stop_option", 'val'=>$options{$2} );
       } else {
	   die "$ProgName ERROR:: bad input to drv_runlength option\n";
       }
   } else {
       add_default($nl, 'stop_option');
       unless (defined $nl->get_value('stop_ymd')) { 
	   add_default($nl, 'stop_n', 'hgrid'=>$lnd_res, 'mask'=>$mask); 
       }
   }

   # Restart interval
   add_default($nl, 'restart_option');

   # Write restart file at end
   add_default($nl, 'end_restart');

   # Start date
   add_default($nl, 'start_ymd', 'hgrid'=>$lnd_res, 'mask'=>$mask);

   # Start tod
   add_default($nl, 'start_tod', 'hgrid'=>$lnd_res, 'mask'=>$mask);

   # Coupling interval
   add_default($nl, 'atm_cpl_dt');
}

##############################
# namelist group: pio_inparm #
##############################

if ($mode eq "ccsm_seq" && $pio eq "on") {

   add_default($nl, 'cpl_io_stride'   );
   add_default($nl, 'cpl_io_numtasks' );
   add_default($nl, 'cpl_io_typename' );
   add_default($nl, 'cpl_io_root'     );

}

##############################
# namelist group: clm_inparm #
##############################

add_default($nl, 'dtime');

if ( $start_type =~ /branch/ ) {
   if (not defined $nl->get_value('nrevsn')) {
      die "$ProgName ERROR:: nrevsn is required for a branch type.\n";
   }
}

add_default($nl, 'fatmlndfrc', 'hgrid'=>$res, 'mask'=>$mask);
add_default($nl, 'fsnowoptics' );
add_default($nl, 'fsnowaging' );

if ($res ne $lnd_res) {
    add_default($nl, 'flndtopo'  , 'hgrid'=>$lnd_res, 'mask'=>$mask );
    add_default($nl, 'fatmtopo'  , 'hgrid'=>$res,     'mask'=>$mask );
}

add_default($nl, 'fatmgrid'  , 'hgrid'=>$res );


add_default($nl, 'fpftcon');


add_default($nl, 'co2_ppmv', 'sim_year'=>$sim_year );
add_default($nl, 'co2_type');
#add_default($nl, 'wrtdia',       'val'=> '.false.');
add_default($nl, 'hist_crtinic',  'bgc'=>$bgc );

add_default($nl, 'urban_hac');
add_default($nl, 'urban_traffic');

#
# Optional variables or variables only turned on for specific settings
#

# If River Transport Model turned on
my $rtm = $cfg->get('rtm');
if ( $rtm eq "on" ) {
   add_default($nl, 'frivinp_rtm');
}

# If cpl6 mode or if DUST or CARBON_AERO NOT turned on -- get aerosol deposition rates from datasets
my $dust        = $cfg->get('dust');
my $carbon_aero = $cfg->get('carbon_aero');
if ( $mode eq "ext_ccsm_con" || $dust eq "off" || $carbon_aero eq "off" ) {
   add_default($nl, 'faerdep', 'hgrid'=>$lnd_res, 'sim_year'=>$sim_year,
                    'sim_year_range'=>$sim_year_range, 'rcp'=>$rcp );
}

#
# Deal with options that the user has said are required...
#
my $demand           = $nl->get_value('clm_demand');
$demand              =~ s/\'//g;   # Remove quotes
if ( $demand =~ /.+/ ) { $opts{'clm_demand'} .= ",$demand"; }
my $demand           = $defaults->get_value('clm_demand');
$demand              =~ s/\'//g;   # Remove quotes
if ( $demand =~ /.+/ ) { $opts{'clm_demand'} .= ",$demand"; }
my @demandlist       = split( ",", $opts{'clm_demand'} );
my %settings         = {};
$settings{'hgrid'}          = $res;
$settings{'sim_year'}       = $sim_year;
$settings{'sim_year_range'} = $sim_year_range;
$settings{'mask'}           = $mask;
$settings{'rcp'}            = $rcp;
foreach my $item ( @demandlist ) {
   if ( $item eq "null" ) { next; }
   add_default($nl, $item, %settings );
}
#
# Get surface dataset after fpftdyn so that we can get surface data consistent with it
#
my $fpftdyn = $nl->get_value('fpftdyn');
$fpftdyn =~ s!(.*)/!!;
$fpftdyn =~ s/'//;
$fpftdyn =~ s/"//;
if ( $fpftdyn eq "" ) { $fpftdyn = "null"; }
my $fndepdyn = $nl->get_value('fndepdyn');
$fndepdyn =~ s!(.*)/!!;
$fndepdyn =~ s/'//;
$fndepdyn =~ s/"//;
if ( $fndepdyn eq "" ) { $fndepdyn = "null"; }
add_default($nl, 'fsurdat'   , 'hgrid'=>$lnd_res, 'sim_year'=>$sim_year );
my $fsurdat = $nl->get_value( 'fsurdat' );

# Initial conditions
# The initial date is an attribute in the defaults file which should be matched unless
# the user explicitly requests to ignore the initial date via the -ignore_ic_date option, 
# or just ignore the year of the initial date via the -ignore_ic_year option.

if ( $start_type =~ /cold/ ) {
   if (defined $nl->get_value('finidat')) {
      die "$ProgName ERROR:: setting finidat is incomptable with using start_type=cold.\n";
   }
   add_default($nl, 'finidat', 'val'=>"' '", 'no_abspath'=>1);
}

if (not defined $nl->get_value('finidat')) {
    my $ic_date = $nl->get_value('start_ymd');
    my $nofail = 1;
    my $var = "finidat";
    if ( $start_type =~ /startup/  ) { $nofail = 0; }
    if ($opts{'ignore_ic_date'}) {
	   add_default($nl, $var, 'hgrid'=>$lnd_res, 'mask'=>$mask, 
                    'nofail'=>$nofail, 'fpftdyn'=>$fpftdyn, 'fndepdyn'=>$fndepdyn, 
                    'sim_year'=>$sim_year, 'maxpft'=>$maxpft );
    } elsif ($opts{'ignore_ic_year'}) {
	   add_default($nl, $var, 'hgrid'=>$lnd_res, 'mask'=>$mask, 
                    'ic_md'=>$ic_date, 'nofail'=>$nofail, 'fpftdyn'=>$fpftdyn, 
                    'fndepdyn'=>$fndepdyn, 'sim_year'=>$sim_year, 'maxpft'=>$maxpft );
    } else {
	   add_default($nl, $var, 'hgrid'=>$lnd_res, 'mask'=>$mask, 
                    'ic_ymd'=>$ic_date, 'nofail'=>$nofail, 'fpftdyn'=>$fpftdyn, 
                    'fndepdyn'=>$fndepdyn, 'sim_year'=>$sim_year, 'maxpft'=>$maxpft );
    }
    my $finidat = $nl->get_value($var);
    if ( (not defined $finidat ) || $finidat =~ /null/ ) {
       my $group = $definition->get_group_name($var);
       $nl->set_variable_value($group, $var, "' '" );
    }
}


#
# If CN mode -- get Nitrogen deposition file if available AND fndepdyn NOT set
#
if ( ($bgc eq "cn") && not defined $nl->get_value('fndepdyn') ) {
   add_default($nl, "fndepdat",  'hgrid'=>$lnd_res, 'sim_year'=>$sim_year, 'nofail'=>1 );
}
 
###############################
# namelist group: prof_inparm #
###############################

if ($mode eq "ccsm_seq") {
  add_default($nl, 'profile_barrier');
  add_default($nl, 'profile_disable');
  add_default($nl, 'profile_single_file');
  add_default($nl, 'profile_depth_limit');
  add_default($nl, 'profile_detail_limit');
}
 
####################################
# namelist group: shr_strdata_nml  #
####################################

my $atm_in;
if ($mode eq "ccsm_seq") {

    add_default($nl, 'io_type');
    add_default($nl, 'num_iotasks');
    add_default($nl, 'io_root');
    add_default($nl, 'io_stride');
    add_default($nl, 'num_agg');

    #
    # Set streams text file
    #
    
    my %cycleopts = ('mask'=>$mask,'hgrid'=>$lnd_res);
    my $init_year;
    my $beg_year;
    my $end_year;
    
    # Note that init_year is the model start year from the driver namelist
    if ( $opts{'datm_cycle_init_year'} eq "default" ) {
	my $start_ymd = $nl->get_value('start_ymd');
	$init_year = int( $start_ymd / 10000 );
    } else {
	$init_year = $opts{'datm_cycle_init_year'}; 
    }
    if ( $opts{'datm_cycle_beg_year'} eq "default" ) {
	$beg_year= $defaults->get_value('datm_cycle_beg_year', \%cycleopts);
    } else {
	$beg_year = $opts{'datm_cycle_beg_year'}; 
    }
    if ( $opts{'datm_cycle_end_year'} eq "default" ) {
	$end_year= $defaults->get_value('datm_cycle_end_year', \%cycleopts);
    } else {
	$end_year = $opts{'datm_cycle_end_year'}; 
    }
    if ( $beg_year > $end_year ) {
	print "\n\ndatm_cycle_beg_year=$beg_year datm_cycle_end_year=$end_year\n";
	die "$ProgName ERROR:: datm_cycle_beg_year greater than datm_cycle_end_year\n";
    }
    
    # Get defaults for data manipulation options associated with each stream (mapping, filling, time-interp etc.)

    # Determine options for reading the stream template file (datm.streams.template.xml)
    my %inputopts;
    if ( $opts{'silent'} ) {
	$inputopts{'printing'} = 0;
    } else {
	$inputopts{'printing'} = 1;
    }
    $inputopts{'test'} = $opts{'test'};
    if ( $opts{'datm_source'} eq "default" ) {
	$inputopts{'datasource'}  = $defaults->get_value( 'datm_source' );
    } else {
	$inputopts{'datasource'}  = $opts{'datm_source'};
    }

    # Determine options for reading the stream template file (datm.streams.template.xml)
    my %inputopts;
    if ( $opts{'silent'} ) {
	$inputopts{'printing'} = 0;
    } else {
	$inputopts{'printing'} = 1;
    }
    $inputopts{'test'} = $opts{'test'};
    if ( $opts{'datm_source'} eq "default" ) {
	$inputopts{'datasource'}  = $defaults->get_value( 'datm_source' );
    } else {
	$inputopts{'datasource'}  = $opts{'datm_source'};
    }
    my $var = "datm_source";
    my $datm_source = $inputopts{'datasource'};
    my $val = &quote_string( $datm_source );
    my $group = $definition->get_group_name( $var );
    $nl->set_variable_value($group, $var, $val );
    if (  ! $definition->is_valid_value( $var, $val ) ) {
       my @valid_values   = $definition->get_valid_values( $var );
       die "$nm $var has a value ($val) that is NOT valid. Valid values are: @valid_values\n";
    }

    $inputopts{'ProgName'} = $ProgName;
    $inputopts{'ProgDir'}  = "$cfgdir";
    if ( $datm_source ne "CLM1PT" ) {
	$inputopts{'res'}     = "";
    } else {
	$inputopts{'res'} = $opts{'res'};
    }
    $inputopts{'yearfirst'}  = $beg_year;
    $inputopts{'yearlast'}   = $end_year;
    if ( defined($opts{'datm_data_dir'}) ) {
	$inputopts{'filepath'} = $opts{'datm_data_dir'};
    } else {
        if ( $datm_source ne "CAMHIST.eul64x128_datm6.01" && $datm_source ne "CLM1PT" ) {
	    die "$ProgName ERROR:: Need to specify datm_data_dir directory of where " .
		" datm data is for datasource=$datm_source.\n";
	}
	$inputopts{'filepath'}   = "";
    }
    if ( ! defined($opts{'datm_dom_dir'} ) ) {
	$inputopts{'domainpath'} = "";
	if ( $datm_source =~ /CAMHIST.GENERIC/ ) {
	    die "$ProgName ERROR:: Need to specify datm_dom_dir directory of where " .
		" datm domain data is for datasource=$datm_source.\n";
	}
    } else {
	$inputopts{'domainpath'} = $opts{'datm_dom_dir'};
    }
    if ( ! defined($opts{'datm_domain'}) ) {
	$inputopts{'domain'} = "";
	if ( $datm_source =~ /CAMHIST.GENERIC/ ) {
	    die "$ProgName ERROR:: Need to specify datm_domain name of domain file " .
		" for datasource=$datm_source.\n";
	}
    } else {
	$inputopts{'domain'} = $opts{'datm_domain'};
    }
    $inputopts{'cmdline'}   = $cmdline;
    $inputopts{'csmdata'}   = $inputdata_rootdir;
    $inputopts{'filenames'} = "";
    $inputopts{'case'}      = "";
    $inputopts{'chng_din_lc'} = 1;
    
    if ( $datm_source ne "CLM_QIAN" ) {
       my $outstreams = "$outdirname/" . $defaults->get_value( 'outstreams' );
       add_default($nl, 'streams', 'val' => "$outstreams $init_year $beg_year $end_year");
       add_default($nl, 'mapalgo');
       add_default($nl, 'mapmask');
       add_default($nl, 'tintalgo');
       add_default($nl, 'fillalgo');
       add_default($nl, 'fillmask');
    
       # Read the streams template file
       my $streams = Streams::Template->new( \%inputopts );
       my $template = $defaults->get_value( 'streamstemplate' );
       $streams->Read( "$cfgdir/../../../$template" );
       
       if ( $opts{'test'} ) {
	   $streams->TestFilesExist( "data" );
	   $streams->TestFilesExist( "domain" );
       }
       $streams->Write( $outstreams );
    } else {
       my $ostreams  = undef;
       my $omapalgo  = undef;
       my $omapmask  = undef;
       my $otintalgo = undef;
       my $ofillalgo = undef;
       my $ofillmask = undef;
       my $filepath  = $inputopts{'filepath'};
       foreach my $src ( "Precip", "Solar", "TPQW" ) {
	  $inputopts{'datasource'}  = "$datm_source.$src";
	  $inputopts{'filepath'} = "$filepath/" . $defaults->get_value( "CLM_QIAN_dir.$src" );

          my $outstreams = "$outdirname/" . $defaults->get_value( 'outstreams' ) . ".$src";
          my $mapalgo    = $defaults->get_value( 'mapalgo' );
          my $mapmask    = $defaults->get_value( 'mapmask' );
          my $tintalgo   = $defaults->get_value( "tintalgo.$src" );
          my $fillalgo   = $defaults->get_value( 'fillalgo' );
          my $fillmask   = $defaults->get_value( 'fillmask' );
    
          # Read the streams template file
          my $streams = Streams::Template->new( \%inputopts );
          my $template = $defaults->get_value( 'streamstemplate' );
          $streams->Read( "$cfgdir/../../../$template" );
       
          if ( $opts{'test'} ) {
	      $streams->TestFilesExist( "data" );
	      $streams->TestFilesExist( "domain" );
          }
          $streams->Write( $outstreams );
          if ( ! defined($ostreams) ) {
             $ostreams  = "\"$outstreams $init_year $beg_year $end_year\"";
             $omapalgo  = "\'$mapalgo\'";
             $omapmask  = "\'$mapmask\'";
             $otintalgo = "\'$tintalgo\'";
             $ofillalgo = "\'$fillalgo\'";
             $ofillmask = "\'$fillmask\'";
          } else {
             $ostreams  = "$ostreams,\"$outstreams $init_year $beg_year $end_year\"";
             $omapalgo  .= ",\'$mapalgo\'";
             $omapmask  .= ",\'$mapmask\'";
             $otintalgo .= ",\'$tintalgo\'";
             $ofillalgo .= ",\'$fillalgo\'";
             $ofillmask .= ",\'$fillmask\'";
          }
      }
      add_default($nl, 'streams',  'val' => "$ostreams"  );
      add_default($nl, 'mapalgo',  'val' => "$omapalgo"  );
      add_default($nl, 'mapmask',  'val' => "$omapmask"  );
      add_default($nl, 'tintalgo', 'val' => "$otintalgo" );
      add_default($nl, 'fillalgo', 'val' => "$ofillalgo" );
      add_default($nl, 'fillmask', 'val' => "$ofillmask" );
   }
}

##############################
# namelist group: datm_in    #
##############################

if ($mode eq "ccsm_seq") {
    add_default($nl, 'datamode', 'val'=>'CLMNCEP' );
    add_default($nl, 'domainfile', 'hgrid'=>$res, 'mask'=>$mask); 
    add_default($nl, 'factorfn');
    add_default($nl, 'iradsw');
    add_default($nl, 'vectors');
    add_default($nl, 'decomp');
    add_default($nl, 'atm_in');
    $atm_in = $nl->get_value('atm_in');
    $atm_in =~ s/"|'//g;
    if ( $start_type =~ /branch/ ) {
       # The datm master restart file is currently unused
       #if (not defined $nl->get_value('restfilm')) {
       #   die "$ProgName ERROR:: restfilm is required for a branch type.\n";
       #}
       if (not defined $nl->get_value('restfils')) {
          die "$ProgName ERROR:: restfils is required for a branch type.\n";
       }
    }
}

##############################
# namelist group: modelio    #
##############################

if ($mode eq "ccsm_seq") {
    add_default($nl, 'diri'    );
    add_default($nl, 'diro'    );
}

#-----------------------------------------------------------------------------------------------
# Validate that the entire resultant namelist is valid
#
$definition->validate($nl);


#-----------------------------------------------------------------------------------------------
# Write output files

my $note = "Comment:\n" . 
           "This namelist was created using the following command-line:\n" .
           "    $cfgdir/$ProgName $cmdline\n" .
           "For help on options use: $cfgdir/$ProgName -help";

# CLM component
my @groups = qw(clm_inparm);
my $outfile = "$opts{'dir'}/lnd_in";
$nl->write($outfile, 'groups'=>\@groups, 'note'=>"$note" );
if ($print>=2) { print "Writing clm namelist to $outfile $eol"; }

if ($mode eq "ccsm_seq") {
    # Driver
    @groups = qw(seq_infodata_inparm seq_timemgr_inparm ccsm_pes prof_inparm);
    if ( $pio eq "on" ) { push( @groups, "pio_inparm" ); }
    $outfile = "$opts{'dir'}/drv_in";
    $nl->write($outfile, 'groups'=>\@groups, 'note'=>"$note" );
    if ($print>=2) { print "Writing driver namelist to $outfile $eol"; }

    # DATM7 component
    @groups = qw(shr_strdata_nml);
    $outfile = "$opts{'dir'}/$atm_in";
    $nl->write($outfile, 'groups'=>\@groups, 'note'=>"$note" );
    if ($print>=2) { print "Writing datm_dshr namelist to $outfile $eol"; }

    @groups = qw(datm_nml);
    $outfile = "$opts{'dir'}/datm_in";
    $nl->write($outfile, 'groups'=>\@groups, 'note'=>"$note" );
    if ($print>=2) { print "Writing datm_in namelist to $outfile $eol"; }

    # atm_modelio
    @groups = qw(modelio);
    $outfile = "$opts{'dir'}/atm_modelio.nml";
    $nl->set_variable_value( "modelio", "logfile", "'atm.log'" );
    $nl->write($outfile, 'groups'=>\@groups, 'note'=>"$note" );
    if ($print>=2) { print "Writing atm_modelio.nml namelist to $outfile $eol"; }

    # lnd_modelio
    @groups = qw(modelio);
    $outfile = "$opts{'dir'}/lnd_modelio.nml";
    $nl->set_variable_value( "modelio", "logfile", "'lnd.log'" );
    $nl->write($outfile, 'groups'=>\@groups, 'note'=>"$note" );
    if ($print>=2) { print "Writing lnd_modelio.nml namelist to $outfile $eol"; }
}

#-----------------------------------------------------------------------------------------------

# Output input dataset list.
if ($opts{'inputdata'}) {
    check_input_files($nl,$inputdata_rootdir,$opts{'inputdata'});
}

# END OF MAIN SCRIPT
#===============================================================================================

sub add_default {

# Add a value for the specified variable to the specified namelist object.  The variables
# already in the object have the higher precedence, so if the specified variable is already
# defined in the object then don't overwrite it, just return.
#
# This method checks the definition file and adds the variable to the correct
# namelist group.
#
# The value can be provided by using the optional argument key 'val' in the
# calling list.  Otherwise a default value is obtained from the namelist
# defaults object.  If no default value is found this method throws an exception
# unless the 'nofail' option is set true.
#
# Example 1: Specify the default value $val for the namelist variable $var in namelist
#            object $nl:
#
#  add_default($nl, $var, 'val'=>$val)
#
# Example 2: Add a default for variable $var if an appropriate value is found.  Otherwise
#            don't add the variable
#
#  add_default($nl, $var, 'nofail'=>1)
#
#
# ***** N.B. ***** This routine assumes the following variables are in package main::
#  $definition        -- the namelist definition object
#  $defaults          -- the namelist defaults object
#  $inputdata_rootdir -- CCSM inputdata root directory

    my $nl = shift;     # namelist object
    my $var = shift;    # name of namelist variable
    my %opts = @_;      # options

    # If variable has quotes around it
    if ( $var =~ /'(.+)'/ ) {
       $var = $1;
    }
    # Query the definition to find which group the variable belongs to.  Exit if not found.
    my $group = $definition->get_group_name($var);
    unless ($group) {
	my $fname = $definition->get_file_name();
	die "$ProgName - ERROR: variable \"$var\" not found in namelist definition file $fname.\n";
    }

    # check whether the variable has a value in the namelist object -- if so then skip to end
    my $val = $nl->get_variable_value($group, $var);
    if (! defined $val) {

       # Look for a specified value in the options hash

       if (defined $opts{'val'}) {
	   $val = $opts{'val'};
       }
       # or else get a value from namelist defaults object.
       # Note that if the 'val' key isn't in the hash, then just pass anything else
       # in %opts to the get_value method to be used as attributes that are matched
       # when looking for default values.
       else {
	   $val = $defaults->get_value($var, \%opts);

           # Truncate model_version appropriately
   
           if ( $var eq "model_version" ) {
               $val =~ /(URL: https:\/\/[a-zA-Z0-9._-]+\/)([a-zA-Z0-9\/._-]+)(\/bld\/.+)/;
               $val = $2;
           }
       }

       # if no value is found then exit w/ error (unless 'nofail' option set)
       unless ( defined($val) ) {
	   unless ($opts{'nofail'}) {
	       die "$ProgName - No default value found for $var.\n" . 
                   "            Are defaults provided for this resolution and land mask?\n";
	   }
	   else {
	       return;
	   }
       }

       # query the definition to find out if the variable is an input pathname
       my $is_input_pathname = $definition->is_input_pathname($var);

       # The default values for input pathnames are relative.  If the namelist
       # variable is defined to be an absolute pathname, then prepend
       # the CCSM inputdata root directory.
       if (not defined $opts{'no_abspath'}) {
	   if (defined $opts{'set_abspath'}) {
	       $val = set_abs_filepath($val, $opts{'set_abspath'});
	   } else {
	       if ($is_input_pathname eq 'abs') {
		   $val = set_abs_filepath($val, $inputdata_rootdir);
                   if ( $test_files and ($val !~ /null/) and (! -f "$val") ) {
                      die "$ProgName - file not found: $var = $val\n";
                   }
	       }
	   }
       }

       # query the definition to find out if the variable takes a string value.
       # The returned string length will be >0 if $var is a string, and 0 if not.
       my $str_len = $definition->get_str_len($var);

       # If the variable is a string, then add quotes if they're missing
       if ($str_len > 0) {
	   $val = quote_string($val);
       }

       # set the value in the namelist
       $nl->set_variable_value($group, $var, $val);
    }

}

#-----------------------------------------------------------------------------------------------

sub check_input_files {

# For each variable in the namelist which is an input dataset, check to see if it
# exists locally.
#
# ***** N.B. ***** This routine assumes the following variables are in package main::
#  $definition        -- the namelist definition object

    my $nl                = shift;     # namelist object
    my $inputdata_rootdir = shift;    # if false prints test, else creates inputdata file
    my $outfile           = shift;

    open(OUTFILE, ">>$outfile") if defined $inputdata_rootdir;

    # Look through all namelist groups
    my @groups = $nl->get_group_names();
    foreach my $group (@groups) {

	# Look through all variables in each group
	my @vars = $nl->get_variable_names($group);
	foreach my $var (@vars) {

	    # Is the variable an input dataset?
	    my $input_pathname_type = $definition->is_input_pathname($var);

	    # If it is, check whether it exists locally and print status
	    if ($input_pathname_type) {

		# Get pathname of input dataset
		my $pathname = $nl->get_variable_value($group, $var);
		# Need to strip the quotes
		$pathname =~ s/['"]//g;

		if ($input_pathname_type eq 'abs') {
                    if ($inputdata_rootdir) {
                        $pathname =~ s:$inputdata_rootdir::;
                        print OUTFILE "$var = $pathname\n";
                    }
                    else {
		        if (-e $pathname) {  # use -e rather than -f since the absolute pathname
			                     # might be a directory
			    print "OK -- found $var = $pathname\n";
		        }
		        else {
			    print "NOT FOUND:  $var = $pathname\n";
		        }
                    }
		}
		elsif ($input_pathname_type =~ m/rel:(.+)/o) {
		    # The match provides the namelist variable that contains the
		    # root directory for a relative filename
		    my $rootdir_var = $1;
		    my $rootdir = $nl->get_variable_value($group, $rootdir_var);
		    $rootdir =~ s/['"]//g;
                    if ($inputdata_rootdir) {
                        $pathname = "$rootdir/$pathname";
                        $pathname =~ s:$inputdata_rootdir::;
                        print OUTFILE "$var = $pathname\n";
                    }
                    else {
		        if (-f "$rootdir/$pathname") {
			    print "OK -- found $var = $rootdir/$pathname\n";
		        }
		        else {
			    print "NOT FOUND:  $var = $rootdir/$pathname\n";
		        }
                    }
		}
	    }
	}
    }
    close OUTFILE if defined $inputdata_rootdir;
    return 0 if defined $inputdata_rootdir;
}


#-----------------------------------------------------------------------------------------------

sub set_abs_filepath {

# check whether the input filepath is an absolute path, and if it isn't then
# prepend a root directory

    my ($filepath, $rootdir) = @_;

    # strip any leading/trailing whitespace
    $filepath =~ s/^\s+//;
    $filepath =~ s/\s+$//;
    $rootdir  =~ s/^\s+//;
    $rootdir  =~ s/\s+$//;

    # strip any leading/trailing quotes
    $filepath =~ s/^['"]+//;
    $filepath =~ s/["']+$//;
    $rootdir =~ s/^['"]+//;
    $rootdir =~ s/["']+$//;

    my $out = $filepath;
    unless ( $filepath =~ /^\// ) {  # unless $filepath starts with a /
	$out = "$rootdir/$filepath"; # prepend the root directory
    }
    return $out;
}

#-----------------------------------------------------------------------------------------------


sub absolute_path {
#
# Convert a pathname into an absolute pathname, expanding any . or .. characters.
# Assumes pathnames refer to a local filesystem.
# Assumes the directory separator is "/".
#
  my $path = shift;
  my $cwd = getcwd();  # current working directory
  my $abspath;         # resulting absolute pathname

# Strip off any leading or trailing whitespace.  (This pattern won't match if
# there's embedded whitespace.
  $path =~ s!^\s*(\S*)\s*$!$1!;

# Convert relative to absolute path.

  if ($path =~ m!^\.$!) {          # path is "."
      return $cwd;
  } elsif ($path =~ m!^\./!) {     # path starts with "./"
      $path =~ s!^\.!$cwd!;
  } elsif ($path =~ m!^\.\.$!) {   # path is ".."
      $path = "$cwd/..";
  } elsif ($path =~ m!^\.\./!) {   # path starts with "../"
      $path = "$cwd/$path";
  } elsif ($path =~ m!^[^/]!) {    # path starts with non-slash character
      $path = "$cwd/$path";
  }

  my ($dir, @dirs2);
  my @dirs = split "/", $path, -1;   # The -1 prevents split from stripping trailing nulls
                                     # This enables correct processing of the input "/".

  # Remove any "" that are not leading.
  for (my $i=0; $i<=$#dirs; ++$i) {
      if ($i == 0 or $dirs[$i] ne "") {
	  push @dirs2, $dirs[$i];
      }
  }
  @dirs = ();

  # Remove any "."
  foreach $dir (@dirs2) {
      unless ($dir eq ".") {
	  push @dirs, $dir;
      }
  }
  @dirs2 = ();

  # Remove the "subdir/.." parts.
  foreach $dir (@dirs) {
    if ( $dir !~ /\.\./ ) {
        push @dirs2, $dir;
    } else {
        pop @dirs2;   # remove previous dir when current dir is ..
    }
  }
  if ($#dirs2 == 0 and $dirs2[0] eq "") { return "/"; }
  $abspath = join '/', @dirs2;
  return( $abspath );
}

#-------------------------------------------------------------------------------

sub valid_option {

    my ($val, @expect) = @_;
    my ($expect);

    $val =~ s/^\s+//;
    $val =~ s/\s+$//;
    foreach $expect (@expect) {
	if ($val =~ /^$expect$/i) { return $expect; }
    }
    return undef;
}

#-------------------------------------------------------------------------------

sub validate_options {

    my $source = shift;   # text string declaring the source of the options being validated
    my $cfg    = shift;   # configure object
    my $opts   = shift;   # reference to hash that contains the options

    my ($opt, $old, @expect);
    
    # use_case
    $opt = 'use_case';
    if (defined $opts->{$opt}) {

        if ( $opts->{$opt} ne "list" ) {
	   # create the @expect array by listing the files in $use_case_dir
	   # and strip off the ".xml" part of the filename
	   @expect = ();
	   my @files = glob("$opts->{'use_case_dir'}/*.xml");
	   foreach my $file (@files) {
	       $file =~ m{.*/(.*)\.xml};
	       push @expect, $1;
	   }
   
	   $old = $opts->{$opt};
	   $opts->{$opt} = valid_option($old, @expect)
	       or die "$ProgName - invalid value of $opt ($old) specified in $source\n".
                      "expected one of: @expect\n";
        } else {
           print "Use cases are:...\n\n";
           my @ucases;
           foreach my $file( sort( glob($opts{'use_case_dir'}."/*.xml") ) ) {
              my $use_case;
              if ( $file =~ /\/([^\/]+)\.xml$/ ) {
                 $use_case = $1;
              } else {
                 die << "EOF";
** $ProgName - Bad name for use case file = $file
EOF
              }
              my $uc_defaults = Build::NamelistDefaults->new("$file", $cfg);
              printf "%15s = %s\n", $use_case, $uc_defaults->get_value("use_case_desc");
              push @ucases, $use_case;
           }
           die <<EOF;
$ProgName - use cases: @ucases
EOF
        }
    }
}

#-------------------------------------------------------------------------------

sub list_options {
#
# List the options for different command line values if asked for
#
    my $cfg     = shift;   # configure object
    my $optsref = shift;   # reference to hash that contains the options

    # options to list values that are in the defaults files
    my @opts_list = ( "res", "lnd_res", "mask", "datm_source", "sim_year", 
                      "datm_cycle_beg_year", "datm_cycle_end_year", 
                      "datm_cycle_init_year", "rcp" );
    my %opts;
    foreach my $var ( "res", "mask", "sim_year", "rcp" ) {
       my $val;
       if (      $optsref->{$var} eq "list" ) {
         $val = "default";
       } elsif ( $optsref->{$var} eq "default" ) {
         $val = $defaults->get_value($var, \%opts );
       } else {
         $val = $optsref->{$var};
       }
       my $vname = $var;
       if ( $vname eq "res" ) { $vname = "hgrid"; }
       $opts{$vname} = $val;
    }
    foreach my $opt ( @opts_list ) {
       if (defined $optsref->{$opt}) {

           if ( $optsref->{$opt} eq "list" ) {
               $var = $opt;
               if ( $var eq "lnd_res" ) { $var = "res"; }
               my @valid_values   = $definition->get_valid_values( $var );
               if ( $opt eq "sim_year" ) { 
                   unshift( @valid_values, 
                            $definition->get_valid_values( "sim_year_range" ) );
               }
               unshift( @valid_values, "default" );
               # Strip out quotes and the constant value
               for( my $i = 0; $i <= $#valid_values; $i++ ) {
                  $valid_values[$i] =~ s/('|')//g;
                  if ( $valid_values[$i] eq "constant" ) { $valid_values[$i] = undef; }
               }
               $val= $defaults->get_value($var, \%opts);
               if ( $opt eq "lnd_res" ) { $val = "same as atm resolution given in res option"; }
               if ( $opt eq "datm_cycle_init_year" ) { 
                  unshift( @valid_values, "0 to 9999" );
                  $val = int( $defaults->get_value("start_ymd")/10000 ); 
               }
               die <<EOF;
$ProgName - valid values for $opt: @valid_values
                  default = $val
                  (NOTE: resolution and mask and other settings may influence what the default is)
EOF
           }
       }
    }
    # clm_demand
    my $opt = 'clm_demand';
    if (defined $optsref->{$opt}) {

        if ( $optsref->{$opt} eq "list" ) {
           my @vars = $definition->get_var_names( );
           my @demands = ( "null" );
           foreach my $var ( @vars ) {
              if ( $definition->get_group_name( $var ) ne "clm_inparm" ) { next; }
              if ( defined($defaults->get_value($var, \%opts ) ) ) { 
                 push( @demands, $var );
              }
           }
           die <<EOF;
$ProgName - valid values for $opt: @demands
            any valid namelist item for clm_inparm can be set. However, not all are 
            available in the clm defaults file. The defaults are also dependent on
            resolution and landmask, as well as other settings. Hence, the list above
            will vary depending on what you set for resolution and landmask.
EOF
        }
    }
}

#-------------------------------------------------------------------------------

sub quote_string {
    my $str = shift;
    $str =~ s/^\s+//;
    $str =~ s/\s+$//;
    unless ($str =~ /^['"]/) {        #"'
        $str = "\'$str\'";
    }
    return $str;
}

#-------------------------------------------------------------------------------

sub version {
# The version is found in CLM ChangeLog file.
# $cfgdir is set by the configure script to the name of its directory.

    my ($cfgdir) = @_;

    my $logfile = "$cfgdir/../doc/ChangeLog";

    my $fh = IO::File->new($logfile, '<') or die "** $ProgName - can't open ChangeLog file: $logfile\n";

    while (my $line = <$fh>) {

	if ($line =~ /^Tag name:\s*(\w+)/ ) {
	    print "$1\n";
	    exit;
	}
    }

}

#-------------------------------------------------------------------------------
