#!/usr/bin/env python3
"""
For description and instructions, please see README. Raw GGCMI sowing and harvest dates are on Derecho and Casper at /glade/campaign/cgd/tss/people/samrabin/raw_ggcmi3_v1.01_nc4/
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.crop_calendars.process_ggcmi_shdates import main

if __name__ == "__main__":
    main()

