#!/bin/bash
# Make sure DOUT_S is turned on, as CUPiD only runs after st_archive
./xmlchange DOUT_S=TRUE

# Enable postprocessing which is what turns on running CUPiD for a case
./xmlchange RUN_POSTPROCESSING=TRUE


LND_ROOT=`./xmlquery --value COMP_ROOT_DIR_LND`

CUPID_ROOT=`./xmlquery --value CUPID_ROOT`
# IF CUPID_ROOT is not set, it means case.setup hasn't run yet so run the generate script to get it configured
# This will result in env_postprocess.xml to be created in the case which is then edited below
if [ -z "$CUPID_ROOT" ]; then
   CUPID_ROOT="$LND_ROOT/tools/CUPiD"
   $CUPID_ROOT/helper_scripts/generate_cupid_config_for_cesm_case.py --cesm-root $SRCROOT --case-root .
fi

#
# Set CUPiD parameters for what a CTSM case needs to do
#

# Set the standard CUPiD baseline case to compare to
./xmlchange --force CUPID_BASELINE_CASE='$CASE'
./xmlchange --force CUPID_BASE_STARTDATE='$RUN_STARTDATE'
./xmlchange --force CUPID_BASE_STOP_N='$STOP_N'
# TODO: Make sure STOP_OPTION is nyears
./xmlchange --force CUPID_BASE_STOP_OPTION='$STOP_OPTION'
# TODO: Have this set based on what CLM_BLDNML_OPTS has
./xmlchange CUPID_RUN_TYPE=SP
./xmlchange --force CUPID_STARTDATE='$RUN_STARTDATE'
./xmlchange --force CUPID_STOP_N='$STOP_N'
./xmlchange --force CUPID_STOP_OPTION='$STOP_OPTION'
./xmlchange CUPID_GEN_HTML=FALSE
./xmlchange CUPID_NTASKS=1
./xmlchange CUPID_RUN_ADF=FALSE
./xmlchange CUPID_RUN_ALL=FALSE
./xmlchange CUPID_RUN_LDF=TRUE
./xmlchange CUPID_RUN_LND=TRUE
./xmlchange CUPID_RUN_ROF=TRUE
