#!/bin/bash
# Make sure DOUT_S is turned on, as CUPiD only runs after st_archive
./xmlchange DOUT_S=TRUE

# Enable postprocessing which is what turns on running CUPiD for a case
./xmlchange RUN_POSTPROCESSING=TRUE


LND_ROOT=`./xmlquery --value COMP_ROOT_DIR_LND`

CUPID_ROOT=`./xmlquery --value CUPID_ROOT`
# When I first tried this I thought I needed the following...
if [ -z "$CUPID_ROOT" ]; then
   echo "CUPID settings aren't done yet"
   exit 5
fi

# For a test case, make sure DOUT_S is TRUE
# TODO: Add a proper SystemTest so this is handled correctly in the test
TEST=`./xmlquery --value TEST`
if [ "$TEST" == "TRUE" ]; then
   ./xmlchange DOUT_S=TRUE --file env_test.xml
fi

#
# Set CUPiD parameters for what a CTSM case needs to do
#

# Set the standard CUPiD baseline case to compare to
./xmlchange --force CUPID_BASELINE_CASE='$CASE'
./xmlchange --force CUPID_BASE_STARTDATE='$RUN_STARTDATE'
./xmlchange --force CUPID_BASE_STOP_N='$STOP_N'
# TODO: Make sure STOP_OPTION is nyears
./xmlchange --force CUPID_BASE_STOP_OPTION='$STOP_OPTION'
# TODO: Have this set based on what CLM_BLDNML_OPTS has
./xmlchange CUPID_RUN_TYPE=SP
./xmlchange --force CUPID_STARTDATE='$RUN_STARTDATE'
./xmlchange --force CUPID_STOP_N='$STOP_N'
./xmlchange --force CUPID_STOP_OPTION='$STOP_OPTION'
# TODO: This should maybe be turned on as a smoke test, and to check for the appropriate files in testing
./xmlchange CUPID_GEN_HTML=TRUE
# TODO: Test with running more tasks
./xmlchange CUPID_NTASKS=1
./xmlchange CUPID_RUN_ADF=FALSE
./xmlchange CUPID_RUN_ALL=FALSE
# Use the land_only example
./xmlchange CUPID_EXAMPLE=land_only
# TODO: Get CUPiD working with LDF under CESM
./xmlchange CUPID_RUN_LDF=FALSE
./xmlchange CUPID_RUN_LND=TRUE
# TODO: Test if ROF can be run
./xmlchange CUPID_RUN_ROF=FALSE
