#!/bin/bash
./xmlchange NEONSITE=YELL
./xmlchange PTS_LON=249.45803999999998
./xmlchange PTS_LAT=44.95597
./xmlchange DATM_YR_ALIGN=2019
# NEON precipitation data for this site is missing so end early
# If CLM_USRDAT_NAME is NEON.PRISM you can run to the end of the data
if [[ $CLM_USRDAT_NAME == 'NEON' ]]; then
  # Different default start date and number of months to run for transient case
  ./xmlchange DATM_YR_START=2019
  if  [[ $compset =~ ^HIST ]]; then
    ./xmlchange RUN_STARTDATE=2019-01-01
    if [[ $TEST != "TRUE" ]]; then
      ./xmlchange STOP_N=39
    fi
  fi
fi
