#!/usr/bin/env python
"""CTSM namelist creator"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.lilac_make_runtime_inputs import main

if __name__ == "__main__":
    main()
