blank_issues_enabled: true
contact_links:
  - name: CESM forums
    url: https://bb.cgd.ucar.edu/cesm/forums/ctsm-clm-mosart-rtm.134/
    about: For support with model use, troubleshooting, etc., please use the CTSM forum
