#!/usr/bin/env python3
"""
This is a just top-level skeleton script that calls
daily_to_monthly_clim.py.
The original code (daily_to_monthly_clim.py) is located under the
python/ctsm/cplhist folder.

It creates a 12-month climatology from daily averaged CMEPS coupler
history (CPLHIST) files, for use by DATM.

For full instructions on how to run the code and different options,
please check the python/ctsm/cplhist/daily_to_monthly_clim.py file.

To run this script the following packages are required:
    - netCDF4
    - the NCO commands ncra, ncrcat and ncatted
----------------------------------------------------------------
To see all available options for daily_to_monthly_clim
    ./daily_to_monthly_clim --help
----------------------------------------------------------------
Instructions for running using the conda python environments
and NCO on Derecho:
module load conda nco
../../py_env_create
conda activate ctsm_pylib
"""

import os
import sys

# -- add python/ctsm  to path
_CTSM_PYTHON = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), os.pardir, os.pardir, "python"
)
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.cplhist.daily_to_monthly_clim import main

if __name__ == "__main__":
    main()
