#!/usr/bin/env python3
"""
Description
-----------
fsurdat_modifier is a tool that modifies fsurdat files. It reads a surface
dataset (fsurdat file) and outputs a modified copy of the same file.

Current applications are limited to the simplest CTSM(SP) mode, so bgc, fire,
urban, vic, lake, transient, and crop-related variables in the fsurdat file remain unchanged.

It differs from modify_singlept_site_neon.py in that the latter specifically
modifies soil properties of single-point surface datasets. Some functions
could/should become shared for use by fsurdat_modifier.

It also differs from the subset_data tool in that the latter subsets fsurdat
files to regional or single-point domains. Though subset_data includes some
"modify" functionality when subsetting to single-point, we intend for similar
functionality to be more extensive and more object oriented in fsurdat_modifier.
Again, some functions could/should become shared among these tools.

Files accessed
--------------
This wrapper script accesses
../../python/ctsm/fsurdat_modifier.py
../../python/ctsm/modify_fsurdat.py

Instructions
------------
To run on Cheyenne/Casper
1) Load the following to your local environment:
module load python
ncar_pylib
(Use "deactivate" to reverse the latter.)
2) ./fsurdat_modifier --help  # TODO This doesn't work currently...
for a list of available arguments
3) ./fsurdat_modifier --fsurdat_out output_file.nc [--fsurdat_in input_file.nc
                      --dom_pft int --max_sat_area float --std_elev float
                      --lnd_lat_min float --lnd_lat_max float
                      --lnd_lon_min float --lnd_lon_max float --zero_nonveg]
Arguments in brackets are optional.
Optional arguments --lnd_lat_min --lnd_lat_max --lnd_lon_min --lnd_lon_max
all need to be set in order to work together.

Example
-------
>>> ./fsurdat_modifier --fsurdat_out test.nc

Inputs
------
/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/
surfdata_10x15_78pfts_CMIP6_simyr1850_c170824.nc

Outputs
-------
./test.nc
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.modify_fsurdat.fsurdat_modifier import main

if __name__ == "__main__":
    main()
