#!/usr/bin/env python3
"""
Description
-----------
fsurdat_modifier is a tool that modifies fsurdat files. It reads a surface
dataset (fsurdat file) and outputs a modified copy of the same file.

Current applications are limited to the simplest CTSM(SP) mode, so bgc, fire,
urban, vic, lake, transient, and crop-related variables in the fsurdat file
remain unchanged.

It differs from modify_singlept_site_neon.py in that the latter specifically
modifies soil properties of single-point surface datasets. Some functions
could/should become shared for use by fsurdat_modifier.

It also differs from the subset_data tool in that the latter subsets fsurdat
files to regional or single-point domains. Though subset_data includes some
"modify" functionality when subsetting to single-point, we intend for similar
functionality to be more extensive and more object oriented in
fsurdat_modifier. Again, some functions could/should become shared among
these tools.

Files accessed
--------------
This wrapper script accesses
../../python/ctsm/fsurdat_modifier.py
../../python/ctsm/modify_fsurdat.py

Instructions
------------
To run on Cheyenne/Casper
1) Load the following to your local environment:
module load python
ncar_pylib
(Use "deactivate" to reverse the latter.)
2) Copy, then modify the configure file named modify_template.cfg, which
contains all the arguments needed by the script.
3) Run the script ./fsurdat_modifier pointing to the copied/modified .cfg file,
e.g. modify_users_copy.cfg

Example
-------
>>> ./fsurdat_modifier modify_users_copy.cfg

Inputs
------
/glade/work/slevis/git/mksurfdata_maps_wo_src_masks/python/ctsm/test/testinputs/
surfdata_5x5_amazon_16pfts_Irrig_CMIP6_simyr2000_c171214.nc

Outputs
-------
./fsurdat_out.nc  # or as named by user in the .cfg file
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.modify_fsurdat.fsurdat_modifier import main

if __name__ == "__main__":
    main()
