#!/usr/bin/env python3
"""
Tool that allows user to modify the fsurdat file.
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
#print (_CTSM_PYTHON)
sys.path.insert(1, _CTSM_PYTHON)

# This lives in CTSM pyton/ctsm...
from ctsm.fsurdat_modifier import main

if __name__ == "__main__":
    main()
