#!/usr/bin/env bash

if [ -f doc-builder/build_docs ]; then
    doc-builder/build_docs "$@"
else
    echo "Obtain doc-builder by running ./manage_externals/checkout_externals -o from the top-level"
fi
