#!/usr/bin/env bash
set -e

if [ -f doc-builder/build_docs ]; then
    echo "Running: make fetch-images"
    make fetch-images
    echo "Running: ./doc-builder/build_docs $@"
    ./doc-builder/build_docs "$@"
else
    echo "Obtain doc-builder by running './bin/git-fleximod update --optional' from the top-level" >&2
    exit 1
fi

exit 0
