#!/bin/bash

# This testmod should only ever be run with a FatesSp compset. Why not just set use_fates_sp in user_nl_clm? Because there are (or may be) *other* things set in a FatesSp compset, so if this test doesn't use one, it's not representative.
compset="$(./xmlquery COMPSET --value)"
if [[ "${compset}" != *"FATES-SP"* ]]; then
    echo "FatesColdSatPhenCamLndTuningMode testmod should only ever be run with a FatesSp compset; this test has compset ${compset}" >&2
    exit 1
fi

./xmlchange LND_TUNING_MODE="clm6_0_cam7.0"
./xmlchange ROF_NCPL='$ATM_NCPL',GLC_NCPL='$ATM_NCPL'

