#!/bin/bash
./xmlchange CLM_FORCE_COLDSTART="on"

# We use this testmod in a _Ln1 test; this requires forcing the ROF coupling frequency to same frequency as DATM
./xmlchange ROF_NCPL='$ATM_NCPL'

# Turn MEGAN off to run faster
./xmlchange CLM_BLDNML_OPTS='--no-megan' --append

# Use fast structure and NWP configuration for speed
./xmlchange CLM_STRUCTURE="fast"
./xmlchange CLM_CONFIGURATION="nwp"

# Turn cpl history off
./xmlchange HIST_OPTION="never"