#!/bin/bash
./xmlchange CLM_FORCE_COLDSTART="on"

# We use this testmod in a _Ln1 test; this requires forcing the ROF coupling frequency to every time step
./xmlchange ROF_NCPL=48

# Restarts aren't allowed for these tests, and turn off CPL history
./xmlchange REST_OPTION="never"
./xmlchange HIST_OPTION="never"
