#!/bin/bash
./xmlchange NEONSITE=MOAB
./xmlchange PTS_LON=250.61118
./xmlchange PTS_LAT=38.25136
./xmlchange DATM_YR_END=2020
if  [[ `./xmlquery CLM_NML_USE_CASE --value` =~ .+_transient  ]]; then
  ./xmlchange STOP_N=36
fi
