#!/bin/bash
./xmlchange NEONSITE=MOAB
./xmlchange PTS_LON=250.61118
./xmlchange PTS_LAT=38.25136
# NEON precipitation data for this site is missing so end early
# If CLM_USRDAT_NAME is NEON.PRISM you can run to the end of the data
if [[ $CLM_USRDAT_NAME == 'NEON' ]]; then
  ./xmlchange DATM_YR_END=2020
  # Different default number of months to run for transient case
  if  [[ $compset =~ ^HIST ]]; then
    ./xmlchange DATM_YR_END=2021
    if [[ $TEST != "TRUE" ]]; then
      ./xmlchange STOP_N=36
    fi
  fi
fi
