!===================================================
! DO NOT EDIT THIS FILE, it was generated using /glade/p/work/erik/clm_collapse/cime/src/externals/genf90/genf90.pl
! Any changes you make to this file may be lost
!===================================================
module array_utils

  ! ------------------------------------------------------------------------
  ! !DESCRIPTION:
  ! This module contains routines for working with arrays.
  !
  ! NOTE(wjs, 2015-10-21) These routines could be moved to csm_share. However, I'm not
  ! sure if these routines will stick around for long, since they are just here to work
  ! around the fact that we don't specify -Mallocatable=03 with pgi (which in turn is
  ! because that flag led to bugs with pgi14).
  !
  ! !USES:

  use shr_kind_mod, only : r8 => shr_kind_r8, i4=>shr_kind_i4

  implicit none
  private
  save

  ! Public routines

  public :: transpose_wrapper ! wrap the intrinsic transpose function, first allocating the destination array
  public :: pack_wrapper      ! wrap the intrinsic pack function, first allocating the destination array

# 25 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  interface transpose_wrapper
     !TYPE int,double
     module procedure transpose_wrapper_int
     !TYPE int,double
     module procedure transpose_wrapper_double
  end interface transpose_wrapper

# 30 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
contains

  !-----------------------------------------------------------------------
  !TYPE int,double
# 34 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  subroutine transpose_wrapper_int(arr_out, arr_in)
    !
    ! !DESCRIPTION:
    ! Wrap the intrinsic transpose function, doing the necessary allocation of the
    ! destination array
    !
    ! NOTE(wjs, 2015-10-21) This is supposed to be handled for you in Fortran2003. Within
    ! CESM, it currently appears to be handled for all compilers except pgi: It is
    ! handled with intel through the use of '-assume realloc_lhs'. It could be handled
    ! with pgi through the use of '-Mallocatable=03', but we currently don't use that
    ! flag, because it triggered bugs with pgi14.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    integer(i4), allocatable, intent(out) :: arr_out(:,:)
    integer(i4), intent(in) :: arr_in(:,:)
    !
    ! !LOCAL VARIABLES:
    integer :: size1, size2

    character(len=*), parameter :: subname = 'transpose_wrapper_int'
    !-----------------------------------------------------------------------

    size1 = size(arr_in, 1)
    size2 = size(arr_in, 2)
    allocate(arr_out(size2, size1))

    arr_out = transpose(arr_in)

# 64 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  end subroutine transpose_wrapper_int
  !TYPE int,double
# 34 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  subroutine transpose_wrapper_double(arr_out, arr_in)
    !
    ! !DESCRIPTION:
    ! Wrap the intrinsic transpose function, doing the necessary allocation of the
    ! destination array
    !
    ! NOTE(wjs, 2015-10-21) This is supposed to be handled for you in Fortran2003. Within
    ! CESM, it currently appears to be handled for all compilers except pgi: It is
    ! handled with intel through the use of '-assume realloc_lhs'. It could be handled
    ! with pgi through the use of '-Mallocatable=03', but we currently don't use that
    ! flag, because it triggered bugs with pgi14.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    real(r8), allocatable, intent(out) :: arr_out(:,:)
    real(r8), intent(in) :: arr_in(:,:)
    !
    ! !LOCAL VARIABLES:
    integer :: size1, size2

    character(len=*), parameter :: subname = 'transpose_wrapper_double'
    !-----------------------------------------------------------------------

    size1 = size(arr_in, 1)
    size2 = size(arr_in, 2)
    allocate(arr_out(size2, size1))

    arr_out = transpose(arr_in)

# 64 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  end subroutine transpose_wrapper_double

  !-----------------------------------------------------------------------
# 67 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  subroutine pack_wrapper(arr_packed, arr, mask)
    !
    ! !DESCRIPTION:
    ! Wrap the intrinsic pack function, doing the necessary allocation of the destination
    ! array.
    !
    ! NOTE(wjs, 2015-10-21) This is supposed to be handled for you in Fortran2003. Within
    ! CESM, it currently appears to be handled for all compilers except pgi: It is
    ! handled with intel through the use of '-assume realloc_lhs'. It could be handled
    ! with pgi through the use of '-Mallocatable=03', but we currently don't use that
    ! flag, because it triggered bugs with pgi14.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    real(r8), allocatable, intent(out) :: arr_packed(:)
    real(r8), intent(in) :: arr(:)
    logical , intent(in) :: mask(:)
    !
    ! !LOCAL VARIABLES:
    integer :: packed_size

    character(len=*), parameter :: subname = 'pack_wrapper'
    !-----------------------------------------------------------------------

    packed_size = count(mask)
    allocate(arr_packed(packed_size))
    arr_packed = pack(arr, mask)

# 96 "/glade/p/work/erik/clm_collapse/components/clm/src/utils/array_utils.F90.in"
  end subroutine pack_wrapper

end module array_utils
