# -*- mode:Makefile -*-
#
# To generate all surface data sets, run:
# make -f Makefile.data all
#
# To generate a single dataset, run make with the name of the rule you
# want to build. For example, to generate the crop data set for 1x1_numaIA:
#
# make -f Makefile.data crop-numa
#
# NOTE: The default behavior is to parallelize data set creation using
# the batch system by submitting jobs to the interactive queue in the
# background. Standard out and standard error are redirected to a text
# file. To change this behavior, you can comment out the BATCHJOBS and
# BACKGROUND variables and replace them with empty variables.
#
# WARNING: Do not put more than one mksurfdata call per rule. output
# redirection is based on the rule name, and multiple rules will over
# write the previous output or incomprehensively merge output from
# simultaneously running jobs.
#
# Note that we typically use -no_surfdata in rules for transient files, having
# separate rules to make the year-1850 and year-2000 surface datasets. This
# results in extra processes, but ensures that the surface datasets have the
# correct name (rather than having 'hist' or 'rcpXXX' in their file name).
#
BATCHJOBS = execgy
BACKGROUND = &> $@.stdout.txt &

MKSURFDATA = $(BATCHJOBS) ./mksurfdata.pl

STANDARD_RES = 360x720cru,48x96,0.9x1.25,1.9x2.5,10x15,ne30np4

STANDARD = \
	global-present \
	global-present-f45 \
	global-present-ne16np4 \
	global-present-ne120np4 \
	global-historical \
	global-historical-ne120np4 \
	global-transient-f45 \
	global-transient \
	global-transient-ne120np4

TROPICS = \
	tropics-present \
	tropics-historical \
	tropics-transient \
	tropics-atlantic-present \
	tropics-atlantic-transient \
	crop-tropics-present \
	crop-tropics-historical \
	crop-tropics-transient

CROP = \
	crop-global-present \
	crop-global-present-f45 \
	crop-global-present-ne16np4 \
	crop-global-present-ne120np4 \
	crop-numa-present \
	crop-smallville \
	crop-smallville-1850 \
	crop-global-1850 \
	crop-global-1850-f45 \
	crop-global-1850-ne120np4 \
	crop-global-historical \
	crop-global-historical-ne120np4 \
	crop-global-transient-f45 \
	crop-global-transient \
	crop-global-transient-ne120np4

all : standard tropics crop urban landuse-timeseries

#
# standard
#
standard : $(STANDARD)

global-present : FORCE
	$(MKSURFDATA) -no_crop -glc_nec 10 -y 2000 -res $(STANDARD_RES) $(BACKGROUND)

global-present-f45 : FORCE
	$(MKSURFDATA) -no_crop -glc_nec 10 -y 1850,2000 -res 4x5 $(BACKGROUND)

global-present-0.125 : FORCE
	$(MKSURFDATA) -no_crop -hirespft -glc_nec 10 -y 2000 -res 0.125x0.125 $(BACKGROUND)

global-present-ne16np4 : FORCE
	$(MKSURFDATA) -no_crop -glc_nec 10 -y 2000 -res ne16np4 $(BACKGROUND)

global-present-ne120np4 : FORCE
	$(MKSURFDATA) -no_crop -glc_nec 10 -y 2000 -res ne120np4 $(BACKGROUND)

global-historical : FORCE
	$(MKSURFDATA) -no_crop -glc_nec 10 -y 1850 -res $(STANDARD_RES) $(BACKGROUND)

global-historical-ne120np4 : FORCE
	$(MKSURFDATA) -no_crop -glc_nec 10 -y 1850 -res ne120np4 $(BACKGROUND)

global-transient : FORCE
	$(MKSURFDATA) -no_crop -no_surfdata -glc_nec 10 -y 1850-2000 -res $(STANDARD_RES) $(BACKGROUND)

global-transient-ne120np4 : FORCE
	$(MKSURFDATA) -no_crop -no_surfdata -glc_nec 10 -y 1850-2000 -res ne120np4 $(BACKGROUND)

global-transient-f45 : FORCE
	$(MKSURFDATA) -no_crop -no_surfdata -glc_nec 10 -y 1850-2000 -res 4x5 $(BACKGROUND)

#
# tropics
#
tropics : $(TROPICS)

tropics-present : FORCE
	$(MKSURFDATA) -glc_nec 0 -no_crop -y 2000 -res 5x5_amazon,1x1_brazil $(BACKGROUND)

tropics-historical : FORCE
	$(MKSURFDATA) -glc_nec 0 -no_crop -y 1850 -res 1x1_brazil $(BACKGROUND)

tropics-transient : FORCE
	$(MKSURFDATA) -glc_nec 0 -no_crop -no_surfdata -y 1850-2000 -res 1x1_brazil $(BACKGROUND)

tropics-atlantic-present : FORCE
	$(MKSURFDATA) -glc_nec 0 -no_crop -y 2000 -res 1x1_tropicAtl $(BACKGROUND)

tropics-atlantic-transient : FORCE
	$(MKSURFDATA) -glc_nec 0 -no_crop -y 1850-2000 -res 1x1_tropicAtl $(BACKGROUND)

crop-tropics-present : FORCE
	$(MKSURFDATA) -glc_nec 0 -y 2000 -res 5x5_amazon,1x1_brazil $(BACKGROUND)

crop-tropics-historical : FORCE
	$(MKSURFDATA) -glc_nec 0 -y 1850 -res 1x1_brazil $(BACKGROUND)

crop-tropics-transient : FORCE
	$(MKSURFDATA) -glc_nec 0 -no_surfdata -y 1850-2000 -res 1x1_brazil $(BACKGROUND)

#
# crop
#
crop : $(CROP)

crop-global-present : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -r $(STANDARD_RES) $(BACKGROUND)

crop-global-present-0.125 : FORCE
	$(MKSURFDATA) -hirespft -glc_nec 10 -y 2000 -r 0.125x0.125 $(BACKGROUND)

crop-global-present-f45 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850,2000 -res 4x5 $(BACKGROUND)

crop-numa-present : FORCE
	$(MKSURFDATA) -glc_nec 0 -y 2000 -r 1x1_numaIA $(BACKGROUND)

crop-smallville : FORCE
	$(MKSURFDATA) -glc_nec 0 -y 2000 -r 1x1_smallvilleIA \
		-pft_idx 17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78 \
		-pft_frc 6.5,1.5,1.6,1.7,1.8,1.9,1.5,1.6,1.7,1.8,1.9,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5 \
		$(BACKGROUND)

crop-global-present-ne16np4 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -res ne16np4 $(BACKGROUND)

crop-global-present-ne120np4 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 2000 -res ne120np4 $(BACKGROUND)

crop-global-historical : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850 -res $(STANDARD_RES) $(BACKGROUND)

crop-global-historical-ne120np4 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850 -res ne120np4 $(BACKGROUND)

crop-global-transient: FORCE
	$(MKSURFDATA) -no_surfdata -glc_nec 10 -y 1850-2000 -res $(STANDARD_RES) $(BACKGROUND)

crop-global-transient-ne120np4 : FORCE
	$(MKSURFDATA) -no_surfdata -glc_nec 10 -y 1850-2000 -res ne120np4 $(BACKGROUND)

crop-global-transient-f45 : FORCE
	$(MKSURFDATA) -no_surfdata -glc_nec 10 -y 1850-2000 -res 4x5 $(BACKGROUND)

# Note that the smallville 1850 dataset is entirely natural vegetation. This
# facilitates testing a transient case that starts with no crop, and then later
# adds crop (to make sure that it works properly to add crop in a grid cell
# where there used to be no crop).
crop-smallville-1850 : FORCE
	$(MKSURFDATA) -glc_nec 0 -y 1850 -r 1x1_smallvilleIA -pft_idx 13 -pft_frc 100 $(BACKGROUND)

crop-global-1850 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850 -r $(STANDARD_RES) $(BACKGROUND)

crop-global-1850-f45 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850 -r 4x5 $(BACKGROUND)

crop-global-1850-ne120np4 : FORCE
	$(MKSURFDATA) -glc_nec 10 -y 1850 -r ne120np4 $(BACKGROUND)
#
# urban
#
urban : urban-present urban-alpha

urban-present : FORCE
	$(MKSURFDATA) -y 2000 -no_crop -glc_nec 0 -r 1x1_camdenNJ,1x1_vancouverCAN,1x1_mexicocityMEX $(BACKGROUND)

# NOTE(bja, 2015-01) skip abort on invalid data necessary as of 2015-01. See
# /glade/p/cesm/cseg/inputdata/lnd/clm2/surfdata_map/README_c141219
urban-alpha : FORCE
	$(MKSURFDATA) -y 2000 -no_crop -glc_nec 0 -r 1x1_urbanc_alpha -urban_skip_abort_on_invalid_data_check $(BACKGROUND)


#
# landuse timeseries
#
landuse-timeseries : landuse-timeseries-f10 landuse-timeseries-smallville

landuse-timeseries-f10 : FORCE
	$(MKSURFDATA) -no_surfdata -glc_nec 10 -y 1850-2000 -r 10x15 $(BACKGROUND)

landuse-timeseries-smallville : FORCE
	$(MKSURFDATA) -no_surfdata -glc_nec 0 -y 1850-1855 -r 1x1_smallvilleIA \
		-pft_idx 17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78 \
		-pft_frc 6.5,1.5,1.6,1.7,1.8,1.9,1.5,1.6,1.7,1.8,1.9,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5 \
		-dynpft single_point_dynpft_files/landuse_timeseries_smallvilleIA_hist_simyr1850-1855.txt \
		$(BACKGROUND)

#
# clean up the working directory by removing generated files
#
clean : FORCE
	-rm *~

clobber : clean
	-rm surfdata_*.nc surfdata_*.log surfdata_*.namelist

#
# generic rule to force things to happen
#
FORCE :

