#!/usr/bin/env python3
"""
Description
-----------
mesh_mask_modifier is a tool that modifies mesh_mask files. It reads the
mesh_mask files and outputs modified copies of the same files.

Files accessed
--------------
This wrapper script accesses
../../python/ctsm/mesh_mask_modifier.py
../../python/ctsm/modify_mesh_mask.py

Instructions
------------
To run on Cheyenne/Casper
1) Load the following to your local environment:
module load python
ncar_pylib
(Use "deactivate" to reverse the latter.)
2) Copy, then modify the configure file named modify_template.cfg, which
contains all the arguments needed by the script.
3) Run the script ./mesh_mask_modifier pointing to the copied/modified
.cfg file, e.g. modify_users_copy.cfg

Example use-case
----------------
F-Case, modifying the continental geometry

User wants to make the Indian Ocean into grassland. They specify their
own land fraction mask on the CESM 1-degree grid, as well as the area to
be specified as grassland in a netcdf file. This has been obtained by
modifying the default land fraction of CESM. An example netcdf file
containing the masks for such a case is on cheyenne:

/glade/work/slevis/git/mksurfdata_toolchain/tools/modify_fsurdat/fill_indian_ocean/fill_indianocean_slevis.nc

This contains two arrays:
- landfrac = the modified land fraction
- landmask = set to 1 where the new land surface has been specified
(i.e., where grassland needs to be specified) and zero elsewhere

This use-case requires modification to the fsurdat and mesh files. To
modify the former, use the modify_fsurdat tool. See that tool for
instructions. Here are the steps to modify the mesh file:

In your copy of the CTSM (say, ~user/ctsm), go to the appropriate tool:
>>> cd tools/modify_mesh_mask
>>> cp modify_template.cfg modify_fill_indianocean.cfg

Enter the following (or similar) selections in modify_fill_indianocean.cfg:

mesh_mask_in = /glade/p/cesmdata/cseg/inputdata/share/meshes/fv0.9x1.25_141008_polemod_ESMFmesh.nc
mesh_mask_out = fv0.9x1.25_141008_polemod_ESMFmesh_modified.nc
landmask_file = .../path_to_your_copy_of/fill_indianocean.nc

Run the tool
>>> ./mesh_mask_modifier modify_fill_indianocean.cfg

A modified mesh file should appear in the directory where you ran.
Point to this as your mesh file in
~user/ctsm/ccs_config/component_grids_nuopc.xml for domain name gx1v7
(i.e. the ocean domain) before starting your CTSM or CESM simulation.

"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.modify_mesh_mask.mesh_mask_modifier import main

if __name__ == "__main__":
    main()
