# This file is used by py_env_create to install the latest version of the ctsm_pylib conda environment.
name: ctsm_pylib
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - xarray=2025.1.2
  - tqdm=4.67.1
  - scipy=1.15.2
  - netcdf4=1.7.2
  - requests=2.32.3
  - xesmf=0.8.8
  - numba=0.61.0
  - pylint=3.3.4
  - black=25.1.0
  - cartopy=0.24.0
  - matplotlib=3.10.1

  # Used in ctsm_postprocessing repo
  - pytest=8.3.5
  - coverage=7.8.0
