#!/bin/bash
#PBS -A P93300606
#PBS -N job_name
#PBS -j oe
#PBS -q premium
#PBS -l walltime=30:00
##PBS -l select=16:ncpus=36:mpiprocs=9
##PBS -l select=24:ncpus=36:mpiprocs=12
#PBS -l select=32:ncpus=36:mpiprocs=12
##PBS -l select=200:ncpus=36:mpiprocs=12

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

# note for -l input above
# -l select={num_nodes}:ncpus={max_tasks_per_node}:mpiprocs={tasks_per_node}
# note for mpiexec below
# -np {total_tasks}


# Run the model
#mpiexec_mpt -p "%g:" -np 144  /glade/u/home/mvertens/src/ctsm.new_mksurfdata/tools/mksurfdata_esmf/src/mksurfdata
#mpiexec_mpt -p "%g:" -np 288  /glade/u/home/mvertens/src/ctsm.new_mksurfdata/tools/mksurfdata_esmf/src/mksurfdata
 mpiexec_mpt -p "%g:" -np 384  /glade/u/home/mvertens/src/ctsm.new_mksurfdata/tools/mksurfdata_esmf/src/mksurfdata
#mpiexec_mpt -p "%g:" -np 2400 /glade/u/home/mvertens/src/ctsm.new_mksurfdata/tools/mksurfdata_esmf/src/mksurfdata

