#!/bin/bash
#PBS -A P93300641
#PBS -N mksurfdata
#PBS -j oe
#PBS -q regular
#PBS -l walltime=12:00:00
#PBS -l select=64:ncpus=36:mpiprocs=12

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

# note for -l input above
# -l select={num_nodes}:ncpus={max_tasks_per_node}:mpiprocs={tasks_per_node}
# note for mpiexec below
# -np {total_tasks}  = {num_nodes} x {tasks_per_node}

rundir=/glade/work/$USER/git_mvertens/ctsm_1663/tools/mksurfdata_esmf
cd $rundir

# Run the model

# -------------
# Notes
# -------------
# T42 is needed for SCAM
# ne120np4 for high resolution SE dycore
# ne16 for testing SE dycore
# f05 for running full chemistry model
# nldas for NWP working with WRF
# -------------

standard_res_no_crop=( '0.9x1.25' '1.9x2.5' '4x5' )
for res in "${standard_res_no_crop[@]}"; do
  input=`./gen_mksurfdata_namelist.py --nocrop --vic --start-year 2000 --end-year 2000 --res $res | cut -d' ' -f5`
  mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input
done

# -------------

input=`./gen_mksurfdata_namelist.py --nocrop --start-year 2000 --end-year 2000 --res 64x128 | cut -d' ' -f5`
mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input

# -------------

input=`./gen_mksurfdata_namelist.py --nocrop --hires_pft --start-year 2005 --end-year 2005 --res 0.125nldas2 | cut -d' ' -f5`
mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input

# -------------

standard_res=( '0.9x1.25' '1.9x2.5' '10x15' '4x5' 'ne30np4' 'C96' 'ne30pg2' 'ne30pg3' 'ne30pg4' 'ne120np4pg3' 'ne0np4ARCTICGRISne30x8' 'ne0np4ARCTICne30x4' 'ne0np4CONUSne30x8' )
for res in "${standard_res[@]}"; do
  input=`./gen_mksurfdata_namelist.py --start-year 2000 --end-year 2000 --res $res | cut -d' ' -f5`
  mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input

  input=`./gen_mksurfdata_namelist.py --start-year 1850 --end-year 1850 --ssp_rcp SSP5-8.5 --res $res | cut -d' ' -f5`
  mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input
done

# -------------

input=`./gen_mksurfdata_namelist.py --start-year 2000 --end-year 2000 --res ne16np4 | cut -d' ' -f5`
mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input

# -------------

input=`./gen_mksurfdata_namelist.py --hires_pft --start-year 2000 --end-year 2000 --res 0.125x0.125 | cut -d' ' -f5`
mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input

# -------------

resolutions=( '0.47x0.63' 'ne120np4' )
years=( 1850 2000 )
for y in "${years[@]}"; do
  for res in "${resolutions[@]}"; do
    input=`./gen_mksurfdata_namelist.py --start-year $y --end-year $y --res $res | cut -d' ' -f5`
    mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input
  done
done

# -------------

# TODO --no_surfdata option not available, yet
# slevis adding to trans_res: ne120np4, 0.47x0.63
trans_res=( '0.9x1.25' '1.9x2.5' '10x15' 'ne30np4' 'ne0np4ARCTICGRISne30x8' 'ne0np4ARCTICne30x4' 'ne0np4CONUSne30x8' 'ne120np4' '0.47x0.63' )
for res in "${trans_res[@]}"; do
  input=`./gen_mksurfdata_namelist.py --no_surfdata --start-year 1850 --end-year 2000 --res $res | cut -d' ' -f5`
  mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input
done

# -------------

# Crop with future scenarios
# TODO --no_surfdata option not available, yet
future_res=( '0.9x1.25' '1.9x2.5' '10x15' )
ssp_list=( 'SSP1-2.6' 'SSP3-7.0' 'SSP5-3.4' 'SSP2-4.5' 'SSP1-1.9' 'SSP4-3.4' 'SSP4-6.0' 'SSP5-8.5' )
for res in "${future_res[@]}"; do
  for ssp in "${ssp_list[@]}"; do
    input=`./gen_mksurfdata_namelist.py --no_surfdata --start-year 1850 --end-year 2100 --ssp-rcp $ssp --res $res | cut -d' ' -f5`
    mpiexec_mpt -p "%g:" -np 768 ./src/mksurfdata < $input
  done
done

# -------------

