#!/bin/bash
#PBS -A P93300606
#PBS -N job_name
#PBS -j oe
#PBS -q premium
#PBS -l walltime=20:00
##PBS -l select=1:ncpus=36:mpiprocs=36
##PBS -l select=4:ncpus=36:mpiprocs=36
##PBS -l select=16:ncpus=36:mpiprocs=9
#PBS -l select=24:ncpus=36:mpiprocs=12
##PBS -l select=32:ncpus=36:mpiprocs=12

# note for -l input above
# -l select={num_nodes}:ncpus={max_tasks_per_node}:mpiprocs={tasks_per_node}
# note for mpiexec below
# -np {total_tasks}

#module rm netcdf
#module load netcdf-mpi pnetcdf pio/2.5.5
#make

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

# Determine mksurfdata_in
# fname=`./gen_mksurfdata_namelist.py --start-year 2000 --end-year 2000 --res 1.9x2.5 --vic --glc | cut -d' ' -f5`
# rm -f mksurfdata_in
# ln -s $fname mksurfdata_in

# Run the model
#mpiexec_mpt -p "%g:" -np 144 /glade/u/home/mvertens/src/ctsm.toolchain/tools/mksurfdata_esmf/src/mksurfdata
 mpiexec_mpt -p "%g:" -np 288 /glade/u/home/mvertens/src/ctsm.toolchain/tools/mksurfdata_esmf/src/mksurfdata
#mpiexec_mpt -p "%g:" -np 384 /glade/u/home/mvertens/src/ctsm.toolchain/tools/mksurfdata_esmf/src/mksurfdata
