#!/bin/bash
#PBS -A P93300641
#PBS -N mksurfdata
#PBS -j oe
#PBS -q regular
#PBS -l walltime=30:00
#PBS -l select=16:ncpus=36:mpiprocs=9
##PBS -l select=24:ncpus=36:mpiprocs=12
##PBS -l select=32:ncpus=36:mpiprocs=12
##PBS -l select=200:ncpus=36:mpiprocs=12

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

# note for -l input above
# -l select={num_nodes}:ncpus={max_tasks_per_node}:mpiprocs={tasks_per_node}
# note for mpiexec below
# -np {total_tasks}

rundir=/glade/work/$USER/git_mvertens/ctsm_1663/tools/mksurfdata_esmf
cd $rundir

# Run the model
input=`./gen_mksurfdata_namelist.py --nocrop --start-year 2000 --end-year 2000 --res 1.9x2.5 | cut -d' ' -f5`
mpiexec_mpt -p "%g:" -np 144 ./src/mksurfdata < $input
#mpiexec_mpt -p "%g:" -np 288 ./src/mksurfdata < $input
#mpiexec_mpt -p "%g:" -np 384 ./src/mksurfdata < $input
#mpiexec_mpt -p "%g:" -np 2400 ./src/mksurfdata < $input
