!===================================================
! DO NOT EDIT THIS FILE, it was generated using /glade/p/work/erik/clm_collapse/cime/src/externals/genf90/genf90.pl
! Any changes you make to this file may be lost
!===================================================
module unittestArrayMod

  ! Provides utility functions for working with array inputs to (or outputs from)
  ! subroutines.
  !
  ! The routines here assume that the subgrid structure has been set up via
  ! unittestSubgridMod.

  use shr_kind_mod, only : r8 => shr_kind_r8, i4 => shr_kind_i4
  use shr_infnan_mod, only : nan => shr_infnan_nan, assignment(=)
  use unittestSubgridMod, only : bounds

  implicit none
  private
  save

  ! Create a gridcell-level array filled with a single value; the type of the array is the
  ! same as the type of the input value. If no value is given, an r8 array is returned,
  ! filled with NaNs.
  public :: grc_array

  ! Create a column-level array filled with a single value; the type of the array is the
  ! same as the type of the input value. If no value is given, an r8 array is returned,
  ! filled with NaNs.
  public :: col_array

# 27 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  interface grc_array
     module procedure grc_array_uninit

     !TYPE logical,int,double
     module procedure grc_array_logical
     !TYPE logical,int,double
     module procedure grc_array_int
     !TYPE logical,int,double
     module procedure grc_array_double
  end interface grc_array

# 34 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  interface col_array
     module procedure col_array_uninit

     !TYPE logical,int,double
     module procedure col_array_logical
     !TYPE logical,int,double
     module procedure col_array_int
     !TYPE logical,int,double
     module procedure col_array_double
  end interface col_array

# 41 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
contains

  !-----------------------------------------------------------------------
# 44 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function grc_array_uninit() result(grc_array)
    !
    ! !DESCRIPTION:
    ! Creates a gridcell-level array of r8 values. All elements are set to NaN.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    real(r8), allocatable :: grc_array(:)  ! function result
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'grc_array_uninit'
    !-----------------------------------------------------------------------

    allocate(grc_array(bounds%begg:bounds%endg))
    grc_array(:) = nan

# 62 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function grc_array_uninit

  !-----------------------------------------------------------------------
  !TYPE logical,int,double
# 66 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function grc_array_logical(val) result(grc_array)
    !
    ! !DESCRIPTION:
    ! Creates a gridcell-level array with the same type as val. All elements are set to val.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    logical, allocatable :: grc_array(:) ! function result
    logical, intent(in)  :: val ! all elements in grc_array are set to val
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'grc_array_logical'
    !-----------------------------------------------------------------------

    allocate(grc_array(bounds%begg:bounds%endg))
    grc_array(:) = val

# 85 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function grc_array_logical
  !TYPE logical,int,double
# 66 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function grc_array_int(val) result(grc_array)
    !
    ! !DESCRIPTION:
    ! Creates a gridcell-level array with the same type as val. All elements are set to val.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    integer(i4), allocatable :: grc_array(:) ! function result
    integer(i4), intent(in)  :: val ! all elements in grc_array are set to val
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'grc_array_int'
    !-----------------------------------------------------------------------

    allocate(grc_array(bounds%begg:bounds%endg))
    grc_array(:) = val

# 85 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function grc_array_int
  !TYPE logical,int,double
# 66 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function grc_array_double(val) result(grc_array)
    !
    ! !DESCRIPTION:
    ! Creates a gridcell-level array with the same type as val. All elements are set to val.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    real(r8), allocatable :: grc_array(:) ! function result
    real(r8), intent(in)  :: val ! all elements in grc_array are set to val
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'grc_array_double'
    !-----------------------------------------------------------------------

    allocate(grc_array(bounds%begg:bounds%endg))
    grc_array(:) = val

# 85 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function grc_array_double


  !-----------------------------------------------------------------------
# 89 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function col_array_uninit() result(col_array)
    !
    ! !DESCRIPTION:
    ! Creates a column-level array of r8 values. All elements are set to NaN.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    real(r8), allocatable :: col_array(:)  ! function result
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'col_array_uninit'
    !-----------------------------------------------------------------------

    allocate(col_array(bounds%begc:bounds%endc))
    col_array(:) = nan

# 107 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function col_array_uninit


  !-----------------------------------------------------------------------
  !TYPE logical,int,double
# 112 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function col_array_logical(val) result(col_array)
    !
    ! !DESCRIPTION:
    ! Creates a column-level array with the same type as val. All elements are set to val.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    logical, allocatable :: col_array(:) ! function result
    logical, intent(in)  :: val ! all elements in col_array are set to val
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'col_array_logical'
    !-----------------------------------------------------------------------

    allocate(col_array(bounds%begc:bounds%endc))
    col_array(:) = val

# 131 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function col_array_logical
  !TYPE logical,int,double
# 112 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function col_array_int(val) result(col_array)
    !
    ! !DESCRIPTION:
    ! Creates a column-level array with the same type as val. All elements are set to val.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    integer(i4), allocatable :: col_array(:) ! function result
    integer(i4), intent(in)  :: val ! all elements in col_array are set to val
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'col_array_int'
    !-----------------------------------------------------------------------

    allocate(col_array(bounds%begc:bounds%endc))
    col_array(:) = val

# 131 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function col_array_int
  !TYPE logical,int,double
# 112 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  pure function col_array_double(val) result(col_array)
    !
    ! !DESCRIPTION:
    ! Creates a column-level array with the same type as val. All elements are set to val.
    !
    ! !USES:
    !
    ! !ARGUMENTS:
    real(r8), allocatable :: col_array(:) ! function result
    real(r8), intent(in)  :: val ! all elements in col_array are set to val
    !
    ! !LOCAL VARIABLES:

    character(len=*), parameter :: subname = 'col_array_double'
    !-----------------------------------------------------------------------

    allocate(col_array(bounds%begc:bounds%endc))
    col_array(:) = val

# 131 "/glade/p/work/erik/clm_collapse/components/clm/src/unit_test_shr/unittestArrayMod.F90.in"
  end function col_array_double


end module unittestArrayMod
