#!/usr/bin/env python3

"""
CTSM namelist creator
"""
import sys, os, shutil

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "CIME", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup          import *
from CIME.buildnml                  import create_namelist_infile, parse_input
from CIME.case                      import Case
from CIME.utils                     import expect, run_cmd

logger = logging.getLogger(__name__)

_config_cache_template = """
<?xml version="1.0"?>
<config_definition>
<commandline></commandline>
<entry id="phys" value="{clm_phys}" list="" valid_values="clm4_5,clm5_0,clm5_1">Specifies CTSM physics</entry>
</config_definition>
"""

###############################################################################
def buildnml(case, caseroot, compname):
###############################################################################
    """Build the CTSM namelist """

    # Build the component namelist
    if compname != "ctsm" and compname != "clm":
        raise AttributeError

    lnd_root = case.get_value("COMP_ROOT_DIR_LND")
    din_loc_root = case.get_value("DIN_LOC_ROOT")
    configuration = case.get_value("CLM_CONFIGURATION")
    structure = case.get_value("CLM_STRUCTURE")
    ccsm_co2_ppmv = case.get_value("CCSM_CO2_PPMV")
    clm_co2_type = case.get_value("CLM_CO2_TYPE")
    clm_namelist_opts = case.get_value("CLM_NAMELIST_OPTS")
    clm_bldnml_opts = case.get_value("CLM_BLDNML_OPTS")
    clm_nml_use_case = case.get_value("CLM_NML_USE_CASE")
    clm_force_coldstart = case.get_value("CLM_FORCE_COLDSTART")
    lnd_tuning_mode = case.get_value("LND_TUNING_MODE")
    clm_accelerated_spinup = case.get_value("CLM_ACCELERATED_SPINUP")
    comp_atm = case.get_value("COMP_ATM")
    lnd_grid = case.get_value("LND_GRID")
    ninst_lnd = case.get_value("NINST_LND")
    rundir = case.get_value("RUNDIR")
    run_type = case.get_value("RUN_TYPE")
    run_startdate = case.get_value("RUN_STARTDATE")
    run_refcase = case.get_value("RUN_REFCASE")
    run_refdate = case.get_value("RUN_REFDATE")
    run_reftod = case.get_value("RUN_REFTOD")
    glc_nec = case.get_value("GLC_NEC")
    cism_use_antarctica = case.get_value("CISM_USE_ANTARCTICA")
    mask = case.get_value("MASK_GRID")
    driver = case.get_value("COMP_INTERFACE").lower()

    stream_ndep_year_first = case.get_value("STREAM_NDEP_YEAR_FIRST")
    stream_ndep_year_last = case.get_value("STREAM_NDEP_YEAR_LAST")
    stream_ndep_year_align = case.get_value("STREAM_NDEP_YEAR_ALIGN")
    stream_ndep_dtlimit = case.get_value("STREAM_NDEP_DTLIMIT")
    stream_ndep_data_filename = case.get_value("STREAM_NDEP_DATA_FILENAME")
    stream_ndep_mesh_filename = case.get_value("STREAM_NDEP_MESH_FILENAME")
    stream_ndep_data_varlist = case.get_value("STREAM_NDEP_DATA_VARLIST")
    stream_ndep_taxmode = case.get_value("STREAM_NDEP_TAXMODE")
    stream_ndep_mapalgo = case.get_value("STREAM_NDEP_MAPALGO")
    stream_ndep_tintalgo = case.get_value("STREAM_NDEP_TINTALGO")

    stream_popdens_year_first = case.get_value("CLM_STREAM_POPDENS_YEAR_FIRST")
    stream_popdens_year_last = case.get_value("CLM_STREAM_POPDENS_YEAR_LAST")
    stream_popdens_year_align = case.get_value("CLM_STREAM_POPDENS_YEAR_ALIGN")
    stream_popdens_data_filename = case.get_value("CLM_STREAM_POPDENS_DATA_FILENAME")
    stream_popdens_mesh_filename = case.get_value("CLM_STREAM_POPDENS_MESH_FILENAME")
    stream_popdens_mapalgo = case.get_value("CLM_STREAM_POPDENS_MAPALGO")
    stream_popdens_tintalgo = case.get_value("CLM_STREAM_POPDENS_TINTALGO")

    stream_lightng_year_first = case.get_value("CLM_STREAM_LIGHTNG_YEAR_FIRST")
    stream_lightng_year_last = case.get_value("CLM_STREAM_LIGHTNG_YEAR_LAST")
    stream_lightng_year_align = case.get_value("CLM_STREAM_LIGHTNG_YEAR_ALIGN")
    stream_lightng_data_filename = case.get_value("CLM_STREAM_LIGHTNG_DATA_FILENAME")
    stream_lightng_mesh_filename = case.get_value("CLM_STREAM_LIGHTNG_MESH_FILENAME")
    stream_lightng_mapalgo = case.get_value("CLM_STREAM_LIGHTNG_MAPALGO")
    stream_lightng_tintalgo = case.get_value("CLM_STREAM_LIGHTNG_TINTALGO")

    stream_urbantv_year_first = case.get_value("CLM_STREAM_URBANTV_YEAR_FIRST")
    stream_urbantv_year_last = case.get_value("CLM_STREAM_URBANTV_YEAR_LAST")
    stream_urbantv_year_align = case.get_value("CLM_STREAM_URBANTV_YEAR_ALIGN")
    stream_urbantv_data_filename = case.get_value("CLM_STREAM_URBANTV_DATA_FILENAME")
    stream_urbantv_mesh_filename = case.get_value("CLM_STREAM_URBANTV_MESH_FILENAME")
    stream_urbantv_mapalgo = case.get_value("CLM_STREAM_URBANTV_MAPALGO")
    stream_urbantv_tintalgo = case.get_value("CLM_STREAM_URBANTV_TINTALGO")

    stream_lai_year_first = case.get_value("CLM_STREAM_LAI_YEAR_FIRST")
    stream_lai_year_last = case.get_value("CLM_STREAM_LAI_YEAR_LAST")
    stream_lai_year_align = case.get_value("CLM_STREAM_LAI_YEAR_ALIGN")
    stream_lai_data_filename = case.get_value("CLM_STREAM_LAI_DATA_FILENAME")
    stream_lai_mesh_filename = case.get_value("CLM_STREAM_LAI_MESH_FILENAME")
    stream_lai_mapalgo = case.get_value("CLM_STREAM_LAI_MAPALGO")
    stream_lai_tintalgo = case.get_value("CLM_STREAM_LAI_TINTALGO")

    stream_soilm_year_first = case.get_value("CLM_STREAM_SOILM_YEAR_FIRST")
    stream_soilm_year_last = case.get_value("CLM_STREAM_SOILM_YEAR_LAST")
    stream_soilm_year_align = case.get_value("CLM_STREAM_SOILM_YEAR_ALIGN")
    stream_soilm_data_filename = case.get_value("CLM_STREAM_SOILM_DATA_FILENAME")
    stream_soilm_mesh_filename = case.get_value("CLM_STREAM_SOILM_MESH_FILENAME")
    stream_soilm_mapalgo = case.get_value("CLM_STREAM_SOILM_MAPALGO")
    stream_soilm_tintalgo = case.get_value("CLM_STREAM_SOILM_TINTALGO")

    stream_ch4finundated_data_filename = case.get_value("CLM_STREAM_CH4FINUNDATED_DATA_FILENAME")
    stream_ch4finundated_mesh_filename = case.get_value("CLM_STREAM_CH4FINUNDATED_MESH_FILENAME")

    # Create init_generated_files directory if not there
    newdir = os.path.join(rundir,"init_generated_files")
    if not os.path.exists(newdir):
        os.mkdir(newdir)

    # -----------------------------------------------------
    # Error checking
    # -----------------------------------------------------
    if ( clm_bldnml_opts.find("-namelist") >= 0 ):
        expect(False, "The -namelist option is NOT allowed to be part of CLM_BLDNML_OPTS, " + \
               "use the CLM_NAMELIST_OPTS option or add namelist items to user_nl_clm instead " );

    # -----------------------------------------------------
    # Set ctsmconf
    # -----------------------------------------------------

    ctsmconf = os.path.join(caseroot, "Buildconf", compname+"conf")
    if not os.path.isdir(ctsmconf):
        os.makedirs(ctsmconf)

    # -----------------------------------------------------
    # Create config_cache.xml file
    # -----------------------------------------------------

    # Note that build-namelist utilizes the contents of the config_cache.xml file in
    # the namelist_defaults.xml file to obtain namelist variables

    clm_phys = case.get_value("CLM_PHYSICS_VERSION")

    config_cache_text = _config_cache_template.format(clm_phys=clm_phys)
    config_cache_path = os.path.join(caseroot, "Buildconf", compname+"conf", "config_cache.xml")
    with open(config_cache_path, 'w') as config_cache_file:
        config_cache_file.write(config_cache_text)

    # -----------------------------------------------------
    # Determine input arguments into build-namelist
    # -----------------------------------------------------

    startfile_type = "finidat"
    start_type = "default"
    if run_type == "hybrid":
        start_type = "startup"
    elif run_type != "startup":
        start_type = run_type

    if run_type == "branch":
        startfile_type = "nrevsn"
        if clm_force_coldstart == "on":
            clm_force_coldstart = "off"
            logger.warning( "WARNING: You've turned on CLM_FORCE_COLDSTART for a branch run_type, which is a contradiction, the coldstart will be ignored\n" +
                            "  turn off CLM_FORCE_COLDSTART, or set RUN_TYPE=hybrid to get rid of this warning")


    if (clm_force_coldstart == "on"):
        logger.warning( "WARNING: CLM is starting up from a cold state" )
        start_type = "cold"

    if lnd_grid == 'T31':
        lnd_grid = '48x96'
    if lnd_grid == 'T42':
        lnd_grid = '64x128'
    if lnd_grid == 'T85':
        lnd_grid = '128x256'
    if lnd_grid == 'T341':
        lnd_grid = '512x1024'

    clmusr = ""
    if lnd_grid == "CLM_USRDAT":
        clm_usrdat_name = case.get_value("CLM_USRDAT_NAME")
        lnd_grid = clm_usrdat_name
        clmusr = " -clm_usr_name %s "%clm_usrdat_name

    if comp_atm != "datm":
        nomeg = "-no-megan"
    else:
        nomeg = ""

    if cism_use_antarctica is None:
        # This is the case for compsets without CISM, where the CISM_USE_ANTARCTICA xml
        # variable isn't defined
        glc_use_antarctica_flag = ""
    elif isinstance(cism_use_antarctica, bool):
        if cism_use_antarctica:
            glc_use_antarctica_flag = "-glc_use_antarctica"
        else:
            glc_use_antarctica_flag = ""
    else:
        expect(False, "Unexpected value for CISM_USE_ANTARCTICA: {}".format(cism_use_antarctica))

    if clm_nml_use_case != "UNSET":
        usecase = "-use_case %s" %clm_nml_use_case
    else:
        usecase = ""

    if ( (mask != "null") and (mask != "UNSET") ):
        gridmask = "-mask %s" %mask
    else:
        gridmask = ""

    start_ymd = run_startdate.replace('-','')

    if ('-01-01' in run_startdate) or ('-09-01' in run_startdate):
        ignore = "-ignore_ic_year"
    else:
        ignore = "-ignore_ic_date"

    tuning = "-lnd_tuning_mode %s "%lnd_tuning_mode

    spinup = "-clm_accelerated_spinup %s "%clm_accelerated_spinup

    infile = os.path.join(ctsmconf, "namelist")

    inputdata_file = os.path.join(caseroot,"Buildconf","ctsm.input_data_list")

    if driver == "nuopc":
        lndfrac_setting = " "
    else:
        lnd_domain_path = case.get_value("LND_DOMAIN_PATH")
        lnd_domain_file = case.get_value("LND_DOMAIN_FILE")
        lndfrac_file = os.path.join(lnd_domain_path,lnd_domain_file)
        lndfrac_setting = "-lnd_frac "+lndfrac_file

    config_cache_file = os.path.join(caseroot,"Buildconf", compname+"conf","config_cache.xml")

    # -----------------------------------------------------
    # Clear out old data
    # -----------------------------------------------------

    if os.path.exists(inputdata_file):
        os.remove(inputdata_file)

    # -----------------------------------------------------
    # loop over instances
    # -----------------------------------------------------

    ninst = int(ninst_lnd)
    for inst_counter in range(1, ninst+1):

        # determine instance string
        inst_string = ""
        if ninst > 1:
            inst_string = '_' + '%04d' % inst_counter

        # If multi-instance case does not have restart file, use
        # single-case restart for each instance
        rpointer = "rpointer.lnd"
        if (os.path.isfile(os.path.join(rundir,rpointer)) and
            (not os.path.isfile(os.path.join(rundir,rpointer + inst_string)))):
            shutil.copy(os.path.join(rundir, rpointer),
                        os.path.join(rundir, rpointer + inst_string))

        # -----------------------------------------------------
        # call build-namelist
        # -----------------------------------------------------

        if run_type == "hybrid" or run_type == "branch":
            compnames = [ "clm4", "clm5", "clm2" ]
            for comp in compnames:
               clm_startfile = "%s.%s%s.r.%s-%s.nc"%(run_refcase,comp,inst_string,run_refdate,run_reftod)
               if os.path.exists(os.path.join(rundir, clm_startfile)):
                 break
               else:
                 clm_startfile = "%s.%s.r.%s-%s.nc"%(run_refcase,comp,run_refdate,run_reftod)
                 if os.path.exists(os.path.join(rundir, clm_startfile)):
                    logger.warning( "WARNING: the start file being used for a multi-instance case is a single instance: "+clm_startfile )
                    break

            if not os.path.exists(os.path.join(rundir, clm_startfile)):
               logger.warning( "WARNING: Could NOT find a start file to use using"+clm_startfile )
            clm_icfile = "%s = \'%s\'"%(startfile_type, clm_startfile)
        else:
            clm_icfile = ""

        infile_lines = []
        infile_lines.append(clm_icfile)

        user_nl_file = os.path.join(caseroot, "user_nl_clm" + inst_string)
        namelist_infile = os.path.join(ctsmconf, "namelist")

        create_namelist_infile(case, user_nl_file, namelist_infile, "\n".join(infile_lines))

        cmd = os.path.join(lnd_root,"bld","build-namelist")
        command = f"{cmd} "
        command = command + f"-driver {driver} "
        command = command + f"-cimeroot {_CIMEROOT} "
        command = command + f"-infile {infile} "
        command = command + f"-csmdata {din_loc_root} "
        command = command + f"-inputdata {inputdata_file} "
        command = command + f"-namelist \"&clm_inparm  start_ymd={start_ymd} {clm_namelist_opts}/ \" "
        command = command + f"{ignore} "
        command = command + f"{nomeg} "
        command = command + f"{usecase} "
        command = command + f"-res {lnd_grid} "
        command = command + f"{clmusr} "
        command = command + f"-clm_start_type {start_type} "
        command = command + f"-envxml_dir {caseroot} "
        command = command + f"-configuration {configuration} "
        command = command + f"-structure {structure} "
        command = command + f"-glc_nec {glc_nec} {glc_use_antarctica_flag} "
        command = command + f"-co2_ppmv {ccsm_co2_ppmv} -co2_type {clm_co2_type} "
        command = command + f"-config {config_cache_file} "
        command = command + f"{clm_bldnml_opts} "
        command = command + f"{spinup} "
        command = command + f"{tuning} "
        command = command + f"{gridmask} "

        command = command + f"-stream_ndep_year_first {stream_ndep_year_first} "
        command = command + f"-stream_ndep_year_last {stream_ndep_year_last} "
        command = command + f"-stream_ndep_year_align {stream_ndep_year_align} "
        command = command + f"-stream_ndep_data_filename {stream_ndep_data_filename} "
        command = command + f"-stream_ndep_mesh_filename {stream_ndep_mesh_filename} "
        command = command + f"-stream_ndep_data_varlist {stream_ndep_data_varlist} "
        command = command + f"-stream_ndep_dtlimit {stream_ndep_dtlimit} "
        command = command + f"-stream_ndep_taxmode {stream_ndep_taxmode} "
        command = command + f"-stream_ndep_mapalgo {stream_ndep_mapalgo} "
        command = command + f"-stream_ndep_tintalgo {stream_ndep_tintalgo} "

        command = command + f"-stream_popdens_year_first {stream_popdens_year_first} "
        command = command + f"-stream_popdens_year_last {stream_popdens_year_last} "
        command = command + f"-stream_popdens_year_align {stream_popdens_year_align} "
        command = command + f"-stream_popdens_data_filename {stream_popdens_data_filename} "
        command = command + f"-stream_popdens_mesh_filename {stream_popdens_mesh_filename} "
        command = command + f"-stream_popdens_mapalgo {stream_popdens_mapalgo} "
        command = command + f"-stream_popdens_tintalgo {stream_popdens_tintalgo} "

        command = command + f"-stream_lightng_year_first {stream_lightng_year_first} "
        command = command + f"-stream_lightng_year_last {stream_lightng_year_last} "
        command = command + f"-stream_lightng_year_align {stream_lightng_year_align} "
        command = command + f"-stream_lightng_data_filename {stream_lightng_data_filename} "
        command = command + f"-stream_lightng_mesh_filename {stream_lightng_mesh_filename} "
        command = command + f"-stream_lightng_mapalgo {stream_lightng_mapalgo} "
        command = command + f"-stream_lightng_tintalgo {stream_lightng_tintalgo} "

        command = command + f"-stream_urbantv_year_first {stream_urbantv_year_first} "
        command = command + f"-stream_urbantv_year_last {stream_urbantv_year_last} "
        command = command + f"-stream_urbantv_year_align {stream_urbantv_year_align} "
        command = command + f"-stream_urbantv_data_filename {stream_urbantv_data_filename} "
        command = command + f"-stream_urbantv_mesh_filename {stream_urbantv_mesh_filename} "
        command = command + f"-stream_urbantv_mapalgo {stream_urbantv_mapalgo} "
        command = command + f"-stream_urbantv_tintalgo {stream_urbantv_tintalgo} "

        command = command + f"-stream_lai_year_last {stream_lai_year_last} "
        command = command + f"-stream_lai_year_align {stream_lai_year_align} "
        command = command + f"-stream_lai_data_filename {stream_lai_data_filename} "
        command = command + f"-stream_lai_mesh_filename {stream_lai_mesh_filename} "
        command = command + f"-stream_lai_mapalgo {stream_lai_mapalgo} "
        command = command + f"-stream_lai_tintalgo {stream_lai_tintalgo} "

        command = command + f"-stream_soilm_year_first {stream_soilm_year_first} "
        command = command + f"-stream_soilm_year_last {stream_soilm_year_last} "
        command = command + f"-stream_soilm_year_align {stream_soilm_year_align} "
        command = command + f"-stream_soilm_data_filename {stream_soilm_data_filename} "
        command = command + f"-stream_soilm_mesh_filename {stream_soilm_mesh_filename} "
        command = command + f"-stream_soilm_mapalgo {stream_soilm_mapalgo} "
        command = command + f"-stream_soilm_tintalgo {stream_soilm_tintalgo} "

        command = command + f"-stream_ch4finundated_data_filename {stream_ch4finundated_data_filename} "
        command = command + f"-stream_ch4finundated_mesh_filename {stream_ch4finundated_mesh_filename} "

        rc, out, err = run_cmd(command, from_dir=ctsmconf)
        expect(rc==0,"Command %s failed rc=%d\nout=%s\nerr=%s"%(cmd,rc,out,err))
        if out is not None:
            logger.debug("     %s"%out)
        if err is not None:
            logger.debug("     %s"%err)

        # -----------------------------------------------------
        # copy resolved namelist to rundir
        # -----------------------------------------------------

        if os.path.isdir(rundir):
            file1 = os.path.join(ctsmconf, "lnd_in")
            file2 = os.path.join(rundir, "lnd_in")
            if ninst > 1:
                file2 += inst_string
            logger.debug("CTSM namelist copy: file1 %s file2 %s " %(file1, file2))
            shutil.copy(file1,file2)

###############################################################################
def _main_func():

    caseroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        compname = case.get_value("COMP_LND")
        logger.warning( "WARNING: buildnml is being called a s program rather than a subroutine " +
                        "as it is expected to be in the CESM context" )
        buildnml(case, caseroot, compname)

if __name__ == "__main__":
    _main_func()
