name: Run checking of the testlist

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'python/ctsm/add_supertestlists.py'
      - 'cime_config/add_supertestlists'
      - 'cime_config/testlist_clm.xml'
  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'python/ctsm/add_supertestlists.py'
      - 'cime_config/add_supertestlists'
      - 'cime_config/testlist_clm.xml'

jobs:
  testlist-supertestlists
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      # Set up the conda environment
      - uses: conda-incubator/setup-miniconda@2defc80cc6f4028b1780c50faf08dd505d698976  # v3
        with:
          activate-environment: ctsm_pylib
          environment-file: python/conda_env_ctsm_py.yml
          channels: conda-forge
          auto-activate-base: false

      # Run add_supertestlists
      - name: Run testlist checker for that lists that should be subsets of others are valid
        run: |
          cd cime_config/testdef
          conda run -n ctsm_pylib ./add_super_testlists --silent --check-only
