name: Check that clm6* compset aliases return CLM6* longnames
# Only check files in our repo that AREN'T in submodules
# Use a Python command to check each file because xmllint isn't available on GH runners

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - '.github/workflows/check-clm6-aliases.sh'
      - 'cime/**'
      - 'cime_config/config_compsets.xml'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - '.github/workflows/check-clm6-aliases.sh'
      - 'cime/**'
      - 'cime_config/config_compsets.xml'

  workflow_dispatch:

jobs:
  check-clm6-aliases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Checkout submodules
        run: |
          bin/git-fleximod update
          
      - name: Install xmllint for CIME
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y libxml2-utils

      - name: Check aliases
        run: |
          .github/workflows/check-clm6-aliases.sh
