name: CIRRUS runner test workflow

on: [push, pull_request] # Trigger on push or pull request

jobs:

  hello-world:
    runs-on: gha-runner-ctsm
    steps:
      - name: Print a little message
        run: echo "Hello, world!"

  list-glade-cesm-input:
    runs-on: gha-runner-ctsm
    steps:
      - name: List Glade inputdata
        run: ls /glade/campaign/cesm/cesmdata/cseg/inputdata

  simple-build:
    name: Build one simple case
    runs-on: gha-runner-ctsm
    steps:

      - name: Check out CTSM
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Checkout all submodules
        run: |
          bin/git-fleximod update -o

      - name: Call run_sys_tests
        run: |
          ./run_sys_tests -t SMS_D_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.clm-default --skip-compare --skip-generate --extra-create-test-args " --no-run" --machine container
