name: Jobs shared by docs workflows that run when a dependency is updated

on:
  workflow_call:
    inputs:
      conda_env_file:
        required: false
        type: string
        default: ""
      conda_env_name:
        required: false
        type: string
        default: ""
    secrets: {}

jobs:
  compare-docbuilder-vs-ctsmpylib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Check out all submodules because we might :literalinclude: something from one
      - name: Checkout all submodules
        run: |
          bin/git-fleximod update doc-builder

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ inputs.conda_env_name }}
          environment-file: ${{ inputs.conda_env_file }}
          channels: conda-forge
          auto-activate-base: false

      - name: Compare docs built with container vs. ctsm_pylib
        run: |
          cd doc/testing
          ./test_container_eq_ctsm_pylib.sh

  makefile-method:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Check out all submodules because we might :literalinclude: something from one
      - name: Checkout all submodules
        run: |
          bin/git-fleximod update doc-builder

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ inputs.conda_env_name }}
          environment-file: ${{ inputs.conda_env_file }}
          channels: conda-forge
          auto-activate-base: false

      - name: Check that Makefile method works
        run: |
          cd doc/testing
          conda run -n ${{ inputs.conda_env_name }} --no-capture-output ./test_makefile_method.sh
