name: Docs tests to run when ctsm_pylib is updated

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'python/conda_env_ctsm_py.txt'
      - 'doc/ctsm-docs_container/requirements.txt'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'python/conda_env_ctsm_py.txt'
      - 'doc/ctsm-docs_container/requirements.txt'

  workflow_dispatch:

permissions:
  contents: read
jobs:
  test-update-dependency:
    name: Tests to run when either docs dependency is updated
    uses: ./.github/workflows/docs-update-dependency-common.yml
    with:
      conda_env_file: python/conda_env_ctsm_py.yml
      conda_env_name: ctsm_pylib
