name: Docs tests to run when doc-builder is updated

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'doc/doc-builder'
      - '.github/workflows/docs-update-dependency-common.yml'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'doc/doc-builder'
      - '.github/workflows/docs-update-dependency-common.yml'

  workflow_dispatch:

permissions:
  contents: read
jobs:
  test-update-dependency:

    name: Tests to run when either docs dependency is updated
    uses: ./.github/workflows/docs-update-dependency-common.yml

  test-rv-setup:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
          lfs: true

      # Check out all submodules because we might :literalinclude: something from one
      - name: Checkout all submodules
        run: |
          bin/git-fleximod update -o

      - name: build_docs rv method
        run: |
          cd doc/test/ && ./test_build_docs_-r-v.sh docker
