name: Test building docs when they're updated
# Does not include a test of building docs with ctsm_pylib; that's in a different Workflow because we only want it to run when ctsm_pylib is updated.

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'doc/**'
      - '!doc/*ChangeLog*'
      - '!doc/*ChangeSum*'
      - '!doc/UpdateChangelog.pl'
      - '.github/workflows/docs-common.yml'
      # Include all include::ed files outside doc/ directory!
      - 'src/README.unit_testing'
      - 'tools/README'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'doc/**'
      - '!doc/*ChangeLog*'
      - '!doc/*ChangeSum*'
      - '!doc/UpdateChangelog.pl'
      - '.github/workflows/docs-common.yml'
      # Include all include::ed files outside doc/ directory!
      - 'src/README.unit_testing'
      - 'tools/README'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  test-build-docs-container:
    if: ${{ always() }}
    name: Using build_docs
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout doc-builder external
        run: |
          manage_externals/checkout_externals doc-builder

      - name: Build docs
        id: build-docs
        run: |
          cd doc && ./build_docs -b ${PWD}/_build -c -d
