name: JupyterBook
#name: Build and Publish JupyterBook to GitHub Pages

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        #pip install git+git://github.com/executablebookproject/cli.git#egg=master
        pip install ghp-import
        #pip install -r book/requirements.txt
        pip install jupyter-book
        PATH="${PATH}:${HOME}/.local/bin"
    - name: Build book TOC file 
      run: |
        docker pull escomp/base
        mkdir ~/ctsm-repos/ctsm-docs
        cd ~/ctsm-repos/ctsm/doc
        ./build_docs -b ~/ctsm-docs -d

