name: Test building docs when they're updated
# Does not include a test of building docs with ctsm_pylib; that's in a different Workflow because we only want it to run when ctsm_pylib is updated.

on:
  push:
    paths:
      - 'doc/**'

  pull_request:
    paths:
      - 'doc/**'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  test-build-docs:
    if: ${{ always() }}
    name: Without ctsm_pylib or container
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: false

  test-build-docs-container:
    if: ${{ always() }}
    name: With container from registry
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout doc-builder external
        run: |
          bin/git-fleximod update doc-builder

      - name: Build docs using container
        id: build-docs
        run: |
          cd doc && ./build_docs -b ${PWD}/_build -c -d
