name: Docs tests to run when ctsm_pylib is updated

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'python/conda_env_ctsm_py.txt'
      - 'doc/ctsm-docs_container/requirements.txt'
      - '.github/workflows/docs-common.yml'
      - '.github/workflows/docs-update-dependency-common.yml'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'python/conda_env_ctsm_py.txt'
      - 'doc/ctsm-docs_container/requirements.txt'
      - '.github/workflows/docs-common.yml'
      - '.github/workflows/docs-update-dependency-common.yml'

  schedule:
    # 8 am every Monday UTC
    - cron: '0 8 * * 1'

  workflow_dispatch:

permissions:
  contents: read
jobs:
  test-build-docs-ctsm_pylib:
    if: ${{ always() }}
    name: Build with ctsm_pylib
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: true
      conda_env_file: python/conda_env_ctsm_py.yml
      conda_env_name: ctsm_pylib

  test-update-dependency:
    if: ${{ always() }}
    name: Docs dependency update tests
    uses: ./.github/workflows/docs-update-dependency-common.yml

  # File an issue if the docs build failed during a scheduled run.
  # The main thing we're concerned about in that case is something having
  # changed outside the repository that's causing the ctsm_pylib setup to
  # fail. Thus, we don't need this job to wait for BOTH the above jobs---
  # if one fails, they both will.
  file-issue-on-failure:
    if: |
      failure() &&
      github.event_name == 'schedule'
    needs: test-build-docs-ctsm_pylib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Create issue
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/workflows/docs-ctsm_pylib.issue_template.md
          update_existing: true
          search_existing: open


