name: Test building docs when they're updated
# Does not include a test of building docs with ctsm_pylib; that's in a different Workflow because we only want it to run when ctsm_pylib is updated.

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    paths:
      - 'doc/**'
      - '!doc/test/*'
      - '!doc/*ChangeLog*'
      - '!doc/*ChangeSum*'
      - '!doc/UpdateChangelog.pl'
      - '.github/workflows/docs-common.yml'
      # Include all include::ed files outside doc/ directory!
      - 'src/README.unit_testing'
      - 'tools/README'
      - 'doc/test/test_container_eq_ctsm_pylib.sh'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'doc/**'
      - '!doc/test/*'
      - '!doc/*ChangeLog*'
      - '!doc/*ChangeSum*'
      - '!doc/UpdateChangelog.pl'
      - '.github/workflows/docs-common.yml'
      # Include all include::ed files outside doc/ directory!
      - 'src/README.unit_testing'
      - 'tools/README'
      - 'doc/test/test_container_eq_ctsm_pylib.sh'

  workflow_dispatch:

permissions:
  contents: read
jobs:

  test-build-docs:
    if: ${{ always() }}
    name: Without ctsm_pylib or container
    uses: ./.github/workflows/docs-common.yml
    with:
      use_conda: false

  test-build-docs-container:
    if: ${{ always() }}
    name: With container from registry
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      # Check out all submodules because we might :literalinclude: something from one
      - name: Checkout all submodules
        run: |
          bin/git-fleximod update -o

      - name: Build docs using Docker (Podman has trouble on GitHub runners)
        id: build-docs
        run: |
          cd doc && ./build_docs -b ${PWD}/_build -c -d
