name: JupyterBook
#name: Build and Publish JupyterBook to GitHub Pages

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        #pip install git+git://github.com/executablebookproject/cli.git#egg=master
        pip install ghp-import
        #pip install -r book/requirements.txt
        pip install jupyter-book
        PATH="${PATH}:${HOME}/.local/bin"
    - name: Build book TOC file 
      run: |
        jupyter-book toc .
    - name: Build book HTML 
      run: |
        jupyter-book build .
    - name: Push _build/html to gh-pages
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        ls -lrt
        ghp-import _build/html -f -p -n
