name: miniconda test
#
# Run the python formatting in check mode
#
on:
  push:
    paths:
      - 'python/**'
      - 'cime_config/SystemTests/**'
      - 'cime_config/buildlib/**'
      - 'cime_config/buildnml/**'
      - '.github/workflows/miniconda.yml'
  pull_request:
    paths:
      - 'python/**'
      - 'cime_config/SystemTests/**'
      - 'cime_config/buildlib/**'
      - 'cime_config/buildnml/**'
      - '.github/workflows/miniconda.yml'

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
