name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/source"
        pre-build-command: "git lfs install && git lfs pull --exclude='' --include=''"
        build-command: "sphinx-build -b html . _build"
