name: "Pull Request Docs Check (Container)"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: escomp/base:latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc"
        pre-build-command: "make fetch-images"
        build-command: "make html"
