name: Check that XML files are well-formed
# Only check files in our repo that AREN'T in submodules
# Use a Python command to check each file because xmllint isn't available on GH runners

on: [push, pull_request] # Trigger on push or pull request

jobs:
  check-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: '3.x'

      - name: Check XML files
        run: python .github/workflows/validate_xml.py
