name: Check that XML files are well-formed

on: [push, pull_request] # Trigger on push or pull request

jobs:
  check-xml-expected-fails:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check XML files for well-formedness
      run: |
        file_list="$(git ls-files '*.xml' --exclude-standard)" # Don't include .xml files in submodules
        n_files=$(echo $file_list | wc -w)
        n_bad=0
        n_checked=0
        for f in ${file_list}; do
          xmllint $f 1>/dev/null 2>&1
          result=$?
          ((n_checked++))
          if [[ ${result} -eq 0 ]]; then
            echo "$f is well-formed"
          else
            echo "* $f is NOT well-formed"
            ((n_bad++))
          fi
        done
        echo ${n_bad}/${n_files} XML files are not well-formed
