#!/bin/sh 
#

if [ $# -ne 6 ]; then
    echo "$0: incorrect number of input arguments" 
    exit 1
fi

optfile=${1%^*}
nlfile=${1#*^}
info=$2
res=${3%^*}
land_res=${3#*^}
mask=${4%@*}
sim_year=${4#*@}
config_file=$5
start_type=$6

cfgdir=${CLM_SCRIPTDIR}/../../bld

if [ "$optfile" = "$1" ]; then
   nlfile="nl_std"
fi
if [ "$mask" = "$4" ]; then
   sim_year="default"
fi
if [ "$res" = "$3" ]; then
   land_res="default"
fi

start_ymd=`echo $info | awk -F: '{print $1}'`
inithist=`echo  $info | awk -F: '{print $2}'`
dtime=`echo     $info | awk -F: '{print $3}'`
if   [ $run_length -ge -2  ] && [ $run_length -le 48   ]; then
   hist_nhtfrq=3
elif [ $run_length -gt -30 ] && [ $run_length -lt 1440 ]; then
   hist_nhtfrq=-24
else
   hist_nhtfrq=0
fi

if [ $run_length -lt 0  ]; then
  length=`expr 0 - $run_length`
  runlen="${length}d"
else
  runlen="${run_length}s"
fi

# Get mode from config file
mode=`grep   "mode="   $config_file | awk -F\" '{print $2}'`
pergro=`grep "pergro=" $config_file | awk -F\" '{print $2}'`

#
# Initialize the following so won't do anything by default
#
restart_file=" "
restbfile=" "
restsfile=" "
logfile=" "
atm_cpl_dt=" "
#
# If branch and a sequential-CCSM simulation -- set restart files using
#
if [ "$mode" = "ccsm_seq" ] && [ "$6" = "branch" ]; then
  if [ -f "$drv_restart" ]; then
     restart_file="restart_file='$drv_restart'"
     restbfile="restbfile='$restBfile'"
     restsfile="restsfile='$restSfile'"
  fi 
fi

#
# If sequential-CCSM -- always do the following...
#
if [ "$mode" = "ccsm_seq" ]; then
  logfile="logfilepostfix='.test.log'"
  atm_cpl_dt="atm_cpl_dt=$dtime"
fi

#
# If pergro -- don't set history frequency
#
if [ "$pergro" = "on" ]; then
  hist_freq=" "
  hist_samp=" "
else
  hist_freq=" hist_nhtfrq=$hist_nhtfrq "
  hist_samp=" hist_mfilt     =  1"
fi


clmopt=`cat ${CLM_SCRIPTDIR}/nl_files/$optfile`
clmnl=${CLM_SCRIPTDIR}/nl_files/$nlfile

echo "$cfgdir/build-namelist -mask $mask -sim_year $sim_year -config $config_file \ "
echo "                 -infile $clmnl -res $res -lnd_res $land_res -start_type $6 \ "
echo "                 -csmdata $CSMDATA -runlength $runlen $clmopt -datm_data_dir $DATM_DATA_DIR \ "
echo "                 -namelist \"\&drv_in start_ymd=$start_ymd $restart_file $restbfile $restsfile $logfile $atm_cpl_dt / \&clm_inparm dtime=$dtime hist_crtinic='$inithist' $hist_samp nrevsn='$nrevsn' $hist_freq /\""

$cfgdir/build-namelist -mask $mask -sim_year $sim_year -config $config_file \
                       -infile $clmnl -res $res -lnd_res $land_res -start_type $6 \
                       -csmdata $CSMDATA -runlength $runlen $clmopt -datm_data_dir $DATM_DATA_DIR \
                       -namelist "\&drv_in start_ymd=$start_ymd $restart_file $restbfile $restsfile $logfile $atm_cpl_dt / \&clm_inparm dtime=$dtime hist_crtinic='$inithist' $hist_samp nrevsn='$nrevsn' $hist_freq /"
