#!/bin/bash
./xmlchange NEONSITE=ONAQ
./xmlchange PTS_LON=247.54755
./xmlchange PTS_LAT=40.17760
if [[$CLM_USRDAT_NAME = 'NEON']]; then
  ./xmlchange DATM_YR_END=2019
fi
# Different default number of months to run for transient case
if  [[ $compset =~ ^HIST ]]; then
  ./xmlchange DATM_YR_END=2020
  ./xmlchange STOP_N=24
fi
